### ISSUE TITLE
Testem global not found

### ISSUE THREAD

**Issue by benoror** [kategengler/ember-cli-code-coverage#1]
Hey @kategengler, I'm glad you finally released this addon 🎉, and also glad to be the first to fill an issue 😄 

When I run the tests I get the following error:

```
$ COVERAGE=true ember test
version: 1.13.13
Built project successfully. Stored in "/Users/benoror/workspace/nimbox/tmp/class-tests_dist-aYKI4ECy.tmp".
not ok 1 PhantomJS 2.1 - global failure
    ---
        actual: >
            null
        message: >
            TypeError: undefined is not a constructor (evaluating 'Testem.afterTests(function(config, data, callback) {
                sendCoverage(callback);
              })')
        Log: |
    ...
...
```

I think it's due to global variable `Testem` not being loaded: https://github.com/kategengler/ember-cli-code-coverage/commit/65821e5f5b26c5a3b613cf62fad35436810417ec#diff-94eab975fb48e219fc130d82e21457acR32

Maybe related to my build script not injecting Testem during tests? Or maybe because of the Ember or Testem version I'm using?

Thanks in advance and kudos for this!

**Comment by kategengler** [comment]
Hi! You need a newer Testem (>= 1.6.0) which comes with a newer ember-cli (2.4.3+ I believe).

**Comment by sfbwalder** [comment]
@kategengler 

We look forward to using istanbul also!  Server side instrumentation is a good idea.

I get the same error Chrome:  ```Uncaught ReferenceError: Testem is not defined```

This line in index.html is failing:  ```Testem.afterTests(function(config, data, callback) {```

I created a new app with ember-cli 2.5 and then installed ember-cli-code-coverage:
* apps package.json:
 ```
"ember-cli": "2.5.0",
"ember-cli-code-coverage": "0.1.0",
```
* apps /node_modules/ember-cli/node_modules/testem/package.json: ```  "version": "1.6.0",```

Thoughts?

cc @ebryn

**Comment by kategengler** [comment]
By any chance are you running the suite at `/tests` rather than through
`ember test -s`?

`/tests` doesn't work yet since I'm relying on that Testem hook, but I hope
to have a fix for that today, at least for QUnit users.

**Comment by sfbwalder** [comment]
Yes, using /tests.  Using QUnit also.  I'll look forward to an update.  Thanks!

**Comment by kategengler** [comment]
Released 0.1.1 with a fix for this for QUnit users. Opened #2 for Mocha support.

**Comment by sfbwalder** [comment]
:+1: Works.  Thanks!

**Comment by didoChulz** [comment]
I can't run the   $ COVERAGE=true ember test   command

**Comment by GCheung55** [comment]
@didoChulz what happens when you execute that command? Any output or errors you can share?

**Comment by didoChulz** [comment]
I got the error **COVERAGE is not an internal or external command** error. 
Do I have to install any node modules for this

**Comment by didoChulz** [comment]
@GCheung55 I got the error COVERAGE is not an internal or external command error. 
Do I have to install any node modules for this
