### ISSUE TITLE
add parallel and coverage-merge example to README

### ISSUE THREAD

**Issue by kellyselden** [kategengler/ember-cli-code-coverage#105]
I haven't figured out how to do it yet, otherwise I would. It's on my todo, someone else feel free to take up this task.

**Comment by rwjblue** [comment]
* Add `parallel: true` to `config/coverage.js`.
* Run `ember exam --split=8 --parallel`
* Run `ember coverage-merge`

Also, note https://github.com/kategengler/ember-cli-code-coverage/issues/102, we need to cleanup the extraneous coverage directories after running `ember coverage-merge`.

**Comment by kellyselden** [comment]
Hmm I believe my use case may be more difficult then. I would have 8 Travis jobs in your scenario. Is it still possible? It's almost like the coverge reporting API would need to understand the reports are coming in pieces.

**Comment by rwwagner90** [comment]
We have tests in place that technically check this is "working", but I don't split my tests myself, so not sure. Can you try 1.0.0-beta.2 @kellyselden?

**Comment by rwwagner90** [comment]
This was just refactored to now only need `COVERAGE=true ember exam --split=8 --parallel` i.e. just use ember exam like you normally would and it should work. We have not released a new beta version yet, but feel free to try out master and let me know if you still see issues!

**Comment by erichonkanen** [comment]
> This was just refactored to now only need COVERAGE=true ember exam --split=8 --parallel
Is this still true? The docs seem to suggest using `ember coverage-merge` for which there is no documentation itself (e.g. should I specify a path if I set coverageFolder var?)
