### ISSUE TITLE
Coverage drop in ember-cli 2.12.2

### ISSUE THREAD

**Issue by denchen** [kategengler/ember-cli-code-coverage#110]
First off, I don't know if this is related to #77 or not. Basically, template files used to be counted, and now they're not.

I was on `ember-cli@2.7.3` and just upgraded to 2.12.2. I also went from 0.2.2 of this library to 0.3.12. Afterwards, I  saw  a sharp drop in coverage. For instance, lines went from 9219/10506 down to 1190/2353. After a cursory bit of digging, I realized it was no longer counting my template files. For instance, in one of my components, previously I had 259/259 lines covered, and now it's 0. And looking at the .hbs in the `/coverage/lcov-report/` directory, it's kinda easy to see why. Whereas before, it looked something like this:

<img width="595" alt="screenshot 2017-04-23 17 08 07" src="https://cloud.githubusercontent.com/assets/2073768/25318623/85fc8aa4-2847-11e7-9a1f-18103ebf4458.png">

Now it looks like this:

<img width="1423" alt="screenshot 2017-04-23 17 08 39" src="https://cloud.githubusercontent.com/assets/2073768/25318624/860f396a-2847-11e7-9329-5ac592086319.png">

Is this due to the new Glimmer engine? Is there some kind of setting I need to get my template files counted again?

**Comment by rwjblue** [comment]
Yes, its related to updating to ember 2.10+ (the templates used to be JavaScript but now they are JSON). https://github.com/kategengler/ember-cli-code-coverage/pull/103 Is attempting to fix this.

**Comment by denchen** [comment]
Thanks for the response. In your estimation, is adding template instrumentation something that will take days, weeks, or months to accomplish? Or another way of puttng it, how high or low is this on your priority list? Thanks again!

**Comment by rwwagner90** [comment]
@adamjmcgrath is going to be tackling template instrumentation, so hopefully we'll get this back soon!
