### ISSUE TITLE
Use .istanbul.yml to configure Istanbul

### ISSUE THREAD

**Issue by ssylvia** [kategengler/ember-cli-code-coverage#112]
Istanbul allows you to add a `.istanbul.yml` file to the root directory of you app to configure Istanbul: https://github.com/gotwarlost/istanbul#configuring.

Can this addon use this in addition to the `config/coverage.js` file?

**Comment by rwwagner90** [comment]
@ssylvia what would be the advantages? Does it allow more configuration of some sort? Curious what the use case is.

**Comment by ssylvia** [comment]
Would allow you to share a config with non-ember apps. Also, I'm still hoping to use the fail test in coverage falls below a specified threshold: https://github.com/kategengler/ember-cli-code-coverage/issues/113

**Comment by rwwagner90** [comment]
@ssylvia ah I see. Would you be interested in helping implement this?

**Comment by ssylvia** [comment]
@rwwagner90 Can't do it immediately, but may be able to look at it in a few weeks or so.

**Comment by rwwagner90** [comment]
I'm going to close this, since you can configure via .istanbul.yml now. Please reopen or file new specific issues around things you specifically would like to see supported via .istanbul.yml.
