### ISSUE TITLE
Running with `COVERAGE=true` generates additional tests that fail

### ISSUE THREAD

**Issue by sergafts** [kategengler/ember-cli-code-coverage#114]
When running `ember test` I see 102 tests, all passing. However, when running tests with `COVERAGE=true ember test` I see 2 additional tests being run and the first of those fails.
Output:

```
...
ok 101 PhantomJS 2.1 - ESLint - utils/currencyutils.js: should pass ESLint
ok 102 PhantomJS 2.1 - ESLint - utils/dateutils.js: should pass ESLint
not ok 103 PhantomJS 2.1 - Global error: TypeError: undefined is not an object (evaluating '_qunit['default'].config.current.assert') at http://localhost:7357/assets/test-support.js, line 5299
    ---
        Log: |
            { type: 'error',
              text: 'TypeError: undefined is not an object (evaluating \'_qunit[\'default\'].config.current.assert\') at http://localhost:7357/assets/test-support.js, line 5299\n' }
    ...
not ok 104 PhantomJS 2.1 - ESLint - utils/dateutils.js: global failure
    ---
        actual: >
            null
        expected: >
            null
        stack: >
            http://localhost:7357/assets/test-support.js:5299
        message: >
            TypeError: undefined is not an object (evaluating '_qunit['default'].config.current.assert')
        Log: |
    ...

1..104
# tests 104
# pass  102
# skip  0
# fail  2
Testem finished with non-zero exit code. Tests failed.
```

The message seems quite cryptic, I could not find why this happens. Could be a misconfiguration on my end, however I don't know how to debug this. Any ideas?

**Comment by sergafts** [comment]
I am using `ember-cli@2.12.0` , `ember-cli-code-coverage@0.3.12`

**Comment by sergafts** [comment]
False positive, issue was on my part. Sorry for the fuss.

**Comment by superthing001** [comment]
@sergafts i have the same issue, not sure what i'm doing wrong.
could you mention what was the problem and how you solved?

**Comment by sergafts** [comment]
@superthing001 My issue was totally irrelevant, and quite cryptic. What helped, though, was gradually deactivating tests & running them one by one. In my case it was an asynchronous event that during testing caused issues.
