### ISSUE TITLE
No coverage information for files in `addon-test-support/`

### ISSUE THREAD

**Issue by job13er** [kategengler/ember-cli-code-coverage#116]
I have an addon whose primary purpose is proving test helpers for use in other addons: [`ember-test-utils`](https://github.com/ciena-blueplanet/ember-test-utils). After [a suggestion from @rwjblue](https://github.com/ciena-blueplanet/ember-test-utils/issues/40) we put that code in `addon-test-support/`. I've now configured `ember-cli-code-coverage` to see if I can make sure we're exercising all the test helpers in that addon, and I can't seem to get the code from `addon-test-support/` to show up in the coverage report. At first, I thought maybe it was being trimmed [here](https://github.com/kategengler/ember-cli-code-coverage/blob/v0.3.12/index.js#L177-L200), but I put a `console.log()` there and I don't see my files being dropped by that function. 

I'll continue to investigate, and submit a PR if I find the issue, but I thought I'd mention it here in case someone with a little more knowledge of this codebase might be able to point me in the right direction.

**Comment by rwwagner90** [comment]
@adamjmcgrath do we currently support coverage for things in `addon-test-support`? If we do, we should probably write tests to make sure we really do, and if not, we should definitely add it.

**Comment by adamjmcgrath** [comment]
We don't currently instrument the `addon-test-support` directory, but it should be relatively simple to add and since it's code that get's shipped with your addon it seems like a good candidate to include.

**Comment by rwwagner90** [comment]
@adamjmcgrath I will work on this later today then. Thanks!

**Comment by rwwagner90** [comment]
This should be fixed now, with the last merge.
