### ISSUE TITLE
Coverage is against transpiled ES5 Code

### ISSUE THREAD

**Issue by sandersky** [kategengler/ember-cli-code-coverage#12]
When using ES6 in my project (also using ES7 decorators via `ember-computed-decorators`), the code coverage being reported is against the transpiled ES5 code. In order to make the coverage report more useful when using services such as *Coveralls* or editor plugins such as *lcov-info* for Atom, the coverage should report against line numbers in the original source code.

**Comment by rwjblue** [comment]
@sandersky - I believe we are correctly reporting against ES6 code ATM (though not esnext as you mentioned RE: decorators).
