### ISSUE TITLE
Can we merge code coverage report generated from different test type say unit and functional?

### ISSUE THREAD

**Issue by mrunalimohane** [kategengler/ember-cli-code-coverage#122]

**Comment by rwjblue** [comment]
Yep! It is documented in the README.

**Comment by mrunalimohane** [comment]
Documentation talks about using with ember exam . What if i do not use ember exam for execution  and run  unit test with coverage true and functional test with coverage true. when i merge the above two coverage file , it creates an coverage folder but the merge is not happening..

**Comment by rwjblue** [comment]
As mentioned in the README, the `ember-exam` was just an example. If you have two coverage folders that match your configured `coverageFolder` path (e.g. `coverage_1` and `coverage_2`), and run `ember coverage-merge` it will merge the two into `coverage` folder.

**Comment by rwjblue** [comment]
Would you mind beefing up the documentation in the README once you get it going?

**Comment by mrunalimohane** [comment]
sure. So i did exactly as you mentioned above when i run the ember coverage-merge , it created coverage folder but the it always creates 
`{
"total":{"lines":{"total":0,"covered":0,"skipped":0,"pct":100},"statements":{"total":0,"covered":0,"skipped":0,"pct":100},"functions":{"total":0,"covered":0,"skipped":0,"pct":100},"branches":{"total":0,"covered":0,"skipped":0,"pct":100},"linesCovered":{}}}
`
