### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by Turbo87** [kategengler/ember-cli-code-coverage#125]
```
Unable to cover: app/utils/geometry.js . Newer JS features may need Babel instumentation to work. Try setting useBabelInstrumenter to true in your config/coverage.js.
 TypeError: Cannot read property 'push' of undefined
    at Instrumenter.instrumentSync (/Users/tbieniek/Code/my-app/node_modules/ember-cli-code-coverage/lib/babel-istanbul-instrumenter.js:42:12)
    at CoverageInstrumenter.processString (/Users/tbieniek/Code/my-app/node_modules/ember-cli-code-coverage/lib/coverage-instrumenter.js:112:25)
    at CoverageInstrumenter.processFile (/Users/tbieniek/Code/my-app/node_modules/broccoli-filter/index.js:165:31)
    at asyncProcessFile (/Users/tbieniek/Code/my-app/node_modules/broccoli-filter/index.js:122:21)
    at tryCatch (/Users/tbieniek/Code/my-app/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/tbieniek/Code/my-app/node_modules/rsvp/dist/rsvp.js:554:13)
    at /Users/tbieniek/Code/my-app/node_modules/rsvp/dist/rsvp.js:629:16
    at flush (/Users/tbieniek/Code/my-app/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

```
$ yarn list ember-cli-code-coverage
yarn list v0.25.1
└─ ember-cli-code-coverage@0.4.1

$ yarn list ember-cli-babel
yarn list v0.25.1
└─ ember-cli-babel@6.4.1
```

`ember-cli-build.js`:

```
babel6: {
  plugins: ['transform-object-rest-spread'],
}
```

Please let me know if you need more information.

**Comment by Turbo87** [comment]
looks like the problem was that we were using `ember-cli@2.12`, with `ember-cli@2.13` everything works as expected. this compat table should probably be mentioned in the README.

**Comment by rwwagner90** [comment]
@Turbo87 does only switching the `ember-cli` version break it? I know there are issues with several of the addons ember-cli uses, so curious if it was just the base package or not.

Also, do you have `useBabelInstrumenter: true` and shouldn't your babel config be `babel` not `babel6`?

**Comment by Turbo87** [comment]
> does only switching the ember-cli version break it?

if I remember correctly that was the single change that fixed it

> do you have `useBabelInstrumenter: true`

yes, I think we had that set

> shouldn't your babel config be babel not babel6?

it depends... 😉

**Comment by rwwagner90** [comment]
@Turbo87 well if everything is working okay now, and you do not have a way to reproduce, I am inclined to close and wait and see if any other issues occur. Thoughts?

**Comment by Turbo87** [comment]
> and you do not have a way to reproduce

I think it should be reproducible if you use the same dependency versions. The main thing I'm proposing in this issue is just to add a compatibility table to the README when there are any obvious incompatibilities.

**Comment by rwwagner90** [comment]
@Turbo87 so you think a new app on cli 2.12 and the latest ember-cli-code-coverage should cause the issue to occur? I would think we would also need to know the content of your `geometry.js` file.

**Comment by Turbo87** [comment]
> I would think we would also need to know the content of your geometry.js file.

as you can see above we're using the `transform-object-rest-spread` plugin and that files uses that (e.g. `let x = { ...y, z };`)

**Comment by rwwagner90** [comment]
@Turbo87 is this still an issue if you use 1.0.0-beta.3 of this addon?

**Comment by Turbo87** [comment]
I don't remember what project this was on or how to reproduce. I'll reopen if I hit this again.
