### ISSUE TITLE
SyntaxError: Use of reserved word 'import'

### ISSUE THREAD

**Issue by lucywyman** [kategengler/ember-cli-code-coverage#128]
My tests run fine without coverage, but when I run `ember exam --split=48 --parallel` all tests fail with the error:
```
not ok 238 PhantomJS 2.1 - Exam Partition #3 - global failure
    ---
        actual: >
            null
        stack: >
            http://localhost:7357/assets/pe-console-app.js:10
        message: >
            SyntaxError: Use of reserved word 'import'
        Log: |
```

I have ember-cli-code-coverage configured to work with parallel tests, and my setup *was* working about a month ago. I'm not sure what could have changed to cause this? I'm working on a fairly big project and there may be code changes I'm not aware of, but I asked coworkers if any changes were suspect and they couldn't think of anything.

Is there anything I should search for, or anything that might be suspect? Unfortunately I'm not usually a js developer, so any (even obvious) information would be helpful! Thank you!

**Comment by alvinvogelzang** [comment]
Same issue here

**Comment by akatz** [comment]
I can confirm this is broken on the latest.
The working version emits code like this:
```
"use strict";



define('application/adapters/application', ['exports', 'ember-data/adapter', 'ember-service/inject'], (function (exports, _emberDataAdapter, _emberServiceInject) {
   var __cov_qYlmtFBdLKVTb_qV_FT4YQ = Function('return this')();
   if (!__cov_qYlmtFBdLKVTb_qV_FT4YQ.__coverage__) {
      __cov_qYlmtFBdLKVTb_qV_FT4YQ.__coverage__ = {};
   }
   __cov_qYlmtFBdLKVTb_qV_FT4YQ = __cov_qYlmtFBdLKVTb_qV_FT4YQ.__coverage__;
```

and the broken version:
```
"use strict";




import Adapter from 'ember-data/adapter';import injectService from 'ember-service/inject';
var __cov_qYlmtFBdLKVTb_qV_FT4YQ = Function('return this')();
if (!__cov_qYlmtFBdLKVTb_qV_FT4YQ.__coverage__) {
   __cov_qYlmtFBdLKVTb_qV_FT4YQ.__coverage__ = {};
}
```

it looks like the latest version drops the definition and only emits the code defined in the module.

**Comment by rwwagner90** [comment]
@lucywyman @alvinvogelzang @akatz can you guys please do me a favor and check what the latest version of ember-cli-code-coverage is that works correctly for you? That way I can look at what has changed since then.

**Comment by rwjblue** [comment]
The underlying ember-cli version is important here also.

**Comment by lucywyman** [comment]
@rwwagner90 the last version I have working is 0.3.12, and ember-cli version 2.12.2

**Comment by rwwagner90** [comment]
@lucywyman would you be able to provide a reproduction repo? All of my addons are on latest ember-cli and latest ember-cli-code-coverage and all my tests have been running smoothly. I'm curious if perhaps the versions of ember-cli and ember-cli-code-coverage you are attempting to use together are just not compatible for some reason.

**Comment by rwwagner90** [comment]
I believe this should be resolved, as of the latest beta. If anyone is still experiencing issues, please let me know and I will reopen this issue.
