### ISSUE TITLE
useBabelInstrumenter:true does not work in ember 2.11

### ISSUE THREAD

**Issue by les2** [kategengler/ember-cli-code-coverage#131]
I'm attempting to use async-await in ember 2.11 *with* code coverage enabled.

- the app will work fine
- tests work fine without coverage (`ember test` will succeed)

But `ember-cli-code-coverage` goes berserk:

```
// config/coverage.js
  useBabelInstrumenter: true,
  babelPlugins: [
    'babel-plugin-transform-async-to-generator',
  ],
```

Running tests with coverage (`COVERAGE=true ember test`) results hundreds of errors like:

```
Unable to cover: app/transforms/foo.js . Newer JS features may need Babel instumentation to work. Try setting useBabelInstrumenter to true in your config/coverage.js.
 ReferenceError: [BABEL] app/transforms/ai-socialcode-audience-type.js: Using removed Babel 5 option: base.modules - Use the corresponding module transform plugin in the `plugins` option. Check out http://babeljs.io/docs/plugins/#modules
```

for every file.

```
 ember --version
ember-cli: 2.11.1
node: 6.11.1
os: darwin x64
```

```
    "ember-cli-code-coverage": "^0.4.1",
```

**Comment by kategengler** [comment]
Is the info in this issue (https://github.com/kategengler/ember-cli-code-coverage/issues/123) helpful?

**Comment by rwwagner90** [comment]
Hi @les2 fancy seeing you here 😄 . Have you taken a look at #123 as @kategengler suggested? I am curious if any of the things done there help this situation.

**Comment by Leooo** [comment]
I'm having the same problem with the following option in ember-cli-build:

```
  options.babel = {
    includePolyfill: true
  };
```

Can't move this option in a plugin as #123 suggested, so stuck on this.

**Comment by rwwagner90** [comment]
@Leooo what version of ember-cli-babel are you on in your project?

**Comment by Leooo** [comment]
@rwwagner90 6.8.2

**Comment by efx** [comment]
Also seeing this in an app running ember-cli-code-coverage@0.4.2 with following ember-cli-build.js:
```js
		babel: {
			debug: true,
			loose: true,
			// following options let us use async/await
			exclude: [
				'transform-async-to-generator',
				'transform-regenerator'
			]
		},
		'ember-cli-babel': {
			includePolyfill: false
		},
```
My `config/coverage.js`: 
```js
module.exports = {
	useBabelInstrumenter: true,
	parallel: true
};
```
```sh
$ ember --version
ember-cli: 2.16.2
node: 8.7.0
os: darwin x64
```

**Comment by alvincrespo** [comment]
I'm also running into this issue as well. The process also doesn't quit, it gets stuck. 

**config/coverage.js**

```
/* eslint-env node */

module.exports = {
  useBabelInstrumenter: true
};
```

**package.json**

```
  "devDependencies": {
    ...
    "ember-cli-babel": "^6.8.2",
    "ember-cli-code-coverage": "^0.4.2",
    ...
  }
```

**ember-cli-build.js**

```
    'ember-cli-babel': {
      includePolyfill: true
    },
```

**Comment by alvincrespo** [comment]
I created an example repo that showcases this issue:

https://github.com/alvincrespo/ember-cli-code-coverage--babel-instrumentation-error

**Comment by alvincrespo** [comment]
I'd like to note, that if there is no `config/coverage.js` we get:

![](https://ac-screenshots.s3.amazonaws.com/1._alvincrespoAlvins-MacBook-Pro_Desktopcoverage-test_zsh_2017-11-03_14-03-28.jpg)

But if we include the `config/coverage.js` with `useBabelInstrumenter` set to true, we get:

![](https://ac-screenshots.s3.amazonaws.com/1._COVERAGEtrue_ember_t_node_2017-11-03_14-03-53.jpg)

**Comment by alvincrespo** [comment]
As noted previously, this appears fixed on master? 

I changed package.json from:

`"ember-cli-code-coverage": "^0.4.2",`

to:

`"ember-cli-code-coverage": "git://github.com/babel/ember-cli-babel",`

**Comment by rwwagner90** [comment]
@alvincrespo looks like you are pulling in `ember-cli-babel` instead of `ember-cli-code-coverage` there.

**Comment by alvincrespo** [comment]
oops - copied the wrong line. Updated my comment above.

**Comment by rwwagner90** [comment]
@alvincrespo that's odd that it works on master. There have been no commits to master since 0.4.2 was released.

**Comment by alvincrespo** [comment]
Yeah, it's super weird. I've been in the weeds for about 3 hours now. Going to rest my 👀 and :brain:

**Comment by Syzygy24** [comment]
Any updates on this?

**Comment by kategengler** [comment]
#141 and #145 have since been landed, which obsoleted the `useBabelInstrumenter` option

**Comment by rwwagner90** [comment]
Agreed. This should be resolved. I know we are running test coverage fine again in the apps @les2 was mentioning, so we should be good here. If anyone is still experiencing issues, please let us know!

**Comment by les2** [comment]
yep, everything's working now!
