### ISSUE TITLE
Terminal output

### ISSUE THREAD

**Issue by eliasdawson** [kategengler/ember-cli-code-coverage#135]
Is it possible to get terminal output of coverage results in addition to the coverage report? Something similar to what's shown on https://istanbul.js.org/.

**Comment by alias-mac** [comment]
I believe that is the `text-summary` report.
Have you tried to set `reporters: ['text-summary']` in your `coverage.js` config file?

**Comment by eliasdawson** [comment]
Ah, that worked. Apologies. I thought I tried that.
