### ISSUE TITLE
Integration Test Breakdown in ember cli code coverage

### ISSUE THREAD

**Issue by jbelmont** [kategengler/ember-cli-code-coverage#136]
Is there a way with Ember CLI Code Coverage or istanbul for that matter to have a Code Coverage Breakdown by Integration, Unit or Acceptance Test?

**Comment by kategengler** [comment]
If you run tests with a filter, you can get coverage provided just by that type of test:

`COVERAGE=true ember test --filter 'Acceptance'` will give you just the coverage provided by your Acceptance tests, assuming they are named with `Acceptance` in the module name.

**Comment by jbelmont** [comment]
I see so we are doing this in an npm script
`ember t -s --filter '!Acceptance |'` which seems to do everything but the Acceptance test.

**Comment by kategengler** [comment]
Then you should be getting the coverage results provided by just those tests that ran.

**Comment by jbelmont** [comment]
Yeah we are, it seems that if we want to explicity get the coverage then it should be done via the filter option, thanks @kategengler
