### ISSUE TITLE
Documentation for use with Travis

### ISSUE THREAD

**Issue by Leooo** [kategengler/ember-cli-code-coverage#143]
Even before considering partitions and ember-exam, could someone explain how things are supposed to work with travis CI, outside of the `COVERAGE=true ember test` line in `.travis.yml`? Few questions I have, probably naive, are:
* Is the `coverage` folder supposed to be created in the repo after the tests run? (for now I've added the folder in .gitignore to not pollute it from local env.)
* Are we, on the other hand, supposed to have a `coverage` folder already existing
* Is there any more post-processing necessary to see the coverage reports from github (like coverall for example)?

Thanks,

L

**Comment by efx** [comment]
When you run COVERAGE=true ember test, it should generate the `coverage` folder. The `lcov.info` file in there has the report. You can use another tool to upload to a service or parse it yourself.
Here is an example `.travis.yml` snippet from my project: 
```yml
script:
- COVERAGE=true ember test
- cat ./coverage/lcov.info | coveralls
```
See https://github.com/nickmerwin/node-coveralls#usage for details if you want to use coveralls.

**Comment by Leooo** [comment]
yes thanks for details! Closing now, hope it will help others
