### ISSUE TITLE
Test resolver undefined

### ISSUE THREAD

**Issue by ZYMoridae** [kategengler/ember-cli-code-coverage#148]
Hi, I met the problem when I use this addon with ember-cli-qunit 3.1 based on ember-cli 2.12. I found that it throws the error which the resolver in the test helper is undefined. I tried to upgrade ember-cli-qunit to 4.x, but still got the same problem. However, I downgraded the ember-cli-code-coverage to 0.1.2 it works but it always generates the empty report.

**Comment by rwwagner90** [comment]
Hi @ZYMoridae can you please try installing ember-cli-code-coverage 1.0.0-beta.2 and see if your problem is gone?

**Comment by ZYMoridae** [comment]
I have reinstalled all dependencies and it works.
