### ISSUE TITLE
Update the location of the configuration path in the documentation

### ISSUE THREAD

**Issue by notmessenger** [kategengler/ember-cli-code-coverage#149]
https://github.com/kategengler/ember-cli-code-coverage#configuration

In `0.3.12` #100 was released that changed the path of the configuration file from _config/coverage.js_ to _tests/config/coverage.js_ (https://github.com/kategengler/ember-cli-code-coverage/commit/317e7dd03240221714f7527429b68ca92d8899ce) and it remains this path in the current version of this addon - https://github.com/kategengler/ember-cli-code-coverage/blob/master/lib/config.js#L23 - but the documentation still references the old path of _config/coverage.js_ and should be updated to reflect _tests/config/coverage.js_

**Comment by kategengler** [comment]
Hi! For apps, `config/coverage.js` will still be the correct location. 

#100 added support for honoring `configPath` which can be set in `package.json` for addons.
