### ISSUE TITLE
1.0.0-beta.0 Coverage directory not being created after running tests

### ISSUE THREAD

**Issue by srini88** [kategengler/ember-cli-code-coverage#150]
I bumped the library to `1.0.0-beta.0` and ran `COVERAGE=true ember test`, it runs successfully without any errors (no babel issues). However, I do not see the `coverage` directory being created.

My `coverage.js` has 

```
module.exports = {
  reporters: ['lcov', 'html'],
  useBabelInstrumenter: true
};
```
It is located in the path `<addon>/tests/dummy/config/coverage.js`. 

I ran it on a mac and also on windows 10, the `coverage` directory does not get created. 
Please let me know if you need more information.

**Comment by adamjmcgrath** [comment]
@srini88 what version of `ember-cli-babel` does your project have?

**Comment by srini88** [comment]
@adamjmcgrath 6.8.2

**Comment by rwwagner90** [comment]
I spoke to @srini88 the issue here is not that it doesn't work, it's that it doesn't work when you have failing tests. I wasn't aware that it generated coverage before with failing tests, but apparently it did. We probably either want to maintain that or document that it no longer works that way.

**Comment by srini88** [comment]
@rwwagner90 @adamjmcgrath  I have all passing tests now in my `<addon>` nevertheless the `coverage` directory hasn't been created. So the issue is still there.

**Comment by adamjmcgrath** [comment]
It should still generate coverage with failing tests (just successfully tested this with a new `ember-cli: 2.18.1` project and failing `util` test). @srini88 Do you have a link to the project?

**Comment by adamjmcgrath** [comment]
If you have any files that throw errors when they're evaluated (like an import error) the coverage result wont be posted to the test middleware.

You could try running `COVERAGE=true ember s` and debugging at this line https://github.com/kategengler/ember-cli-code-coverage/blob/master/lib/templates/test-body-footer.html#L6 in the `tests/index.html` page. 

This library used to catch those errors https://github.com/kategengler/ember-cli-code-coverage/blob/7f9b961b0170580e67b7f60890b30254021ca1c6/lib/templates/test-body-footer.html#L13

**Comment by abishek-srinivasan** [comment]
I use "ember-cli-code-coverage": "1.0.0-beta.1". I am able to run the complete test suite. The coverage directory gets generated. But my coverage/lcov.info is empty without any data. When I check my jenkins Codecov, it says,
Reading reports

Skipping empty file ./coverage/lcov.info
--> No coverage data found.
When I open coverage/lcov-report/index.html, it shows everything as Zero. Something like this

Unknown% Statements 0/0Unknown% Branches 0/0Unknown% Functions 0/0Unknown% Lines 0/0

Checked coverage-summary.json as well. It comes like this,
{"total": {"lines":{"total":0,"covered":0,"skipped":0,"pct":"Unknown"},"statements":{"total":0,"covered":0,"skipped":0,"pct":"Unknown"},"functions":{"total":0,"covered":0,"skipped":0,"pct":"Unknown"},"branches":{"total":0,"covered":0,"skipped":0,"pct":"Unknown"}}
}

My config/coverage.js is as follows:
module.exports = {
  excludes: ['*/mirage/**/*', '*/tests/**/*', '*/vendor/**/*', '*/app/styles/**/*', '*/lib/**/*', '*/assets/**/*', '*/config/**/*'],
  parallel: true,
  coverageEnvVar: true,
  useBabelInstrumenter: true
};
I am using --path flag in my ember exam command and I have set coverageEnvVar to true.
@adamjmcgrath @kategengler @srini88 @rwwagner90 , Am I missing something? Please let me know if you need any other information.

**Comment by rwwagner90** [comment]
@abishek-srinivasan can you please try the latest beta?

**Comment by abishek-srinivasan** [comment]
@rwwagner90 , I will not be able to do that. I use babel 6 and I have to update the babel to 7 if I have to move to latest beta. Is there any way to resolve it with the current version that I am using?

**Comment by rwwagner90** [comment]
You can update ember-cli and/or ember-cli-babel without updating your Ember version, in most cases. I would try updating some things and see if the latest beta works. It may or may not.
