### ISSUE TITLE
1.0.0-beta.0 not instrumenting application files

### ISSUE THREAD

**Issue by wireframe** [kategengler/ember-cli-code-coverage#151]
Testing out latest release 1.0.0-beta.0 and the test coverage report is reporting that only 32 lines exist in my app -- which is just a weee bit off :)

I'm using a vanilla install of ember-cli-code-coverage with no additional configuration ATM, and I'm happy to supply additional information and test various config to help identify the issue.

**Comment by adamjmcgrath** [comment]
Are you a Windows user? I suspect there may be an issue for Windows users with generating the module paths in https://github.com/kategengler/ember-cli-code-coverage/blob/master/index.js#L189

**Comment by wireframe** [comment]
Nope.  macOS user, but we see the exact same coverage report when running on our CI server (CircleCI).

**Comment by kategengler** [comment]
@wireframe Any more info here? Can you reproduce in a repo you can share?

**Comment by wireframe** [comment]
I wish I could share our app, but unfortunately, I can't. 😢 

I'm guessing this isn't an issue with a vanilla new ember app, so it likely has to do with conflicts in our env.  if there's any info I can provide to help troubleshoot, I'm happy to do so (ex: package.json).  For reference, we were long time users of ember-cli-blanket which worked great and we transitioned to ember-cli-code-coverage for a while (needed to remove it due to some random segfaults in CircleCI).  So we're coming back to the plugin with the latest version to test out if the issues still persist.

**Comment by kategengler** [comment]
@wireframe I imagined you wouldn't be able to, I was wondering if you could try to recreate it in a vanilla app by adding things that simulate your app until it doesn't work?

**Comment by rwwagner90** [comment]
@wireframe do you happen to have in-repo addons in your app?

**Comment by wireframe** [comment]
Correct!  We do have two or three small inrepo addons in our app. We also use pods to organize our app Incase that info is helpful.

**Comment by rwwagner90** [comment]
@wireframe can you please try 1.0.0-beta.2? I believe it should fix your issues.

**Comment by wireframe** [comment]
Awesome!  1.0.0-beta.2 is now reporting 88% test coverage for app which seems *much* more accurate!  Thanks!
