### ISSUE TITLE
fails to create `coverage` directory with `--path` flag

### ISSUE THREAD

**Issue by 0xadada** [kategengler/ember-cli-code-coverage#154]
If I use the `ember test` command with the `--path` flag, the addon will not produce a coverage directory or contents. In this use-case I have already produced a build, and I'm reusing that build to run tests.

e.g:
```js
ember build -e test --output-path=dist
COVERAGE=true ember test --path=dist
```

`ember-cli-code-coverage` version 0.4.2

```
$ ember --version --verbose
ember-cli: 2.18.0
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
```

**Comment by adamjmcgrath** [comment]
The code is instrumented for coverage during the build, so you would need to do:

```bash
COVERAGE=true ember build -e test --output-path=dist
COVERAGE=true ember test --path=dist
```

**Comment by 0xadada** [comment]
this worked for me, i'm closing the issue.

**Comment by astronomersiva** [comment]
We should probably add this to the README. Spent a long time chasing this today. Can I go ahead and create a PR for this?

**Comment by rwwagner90** [comment]
@astronomersiva sure thing, PRs are always welcome 😃
