### ISSUE TITLE
Branch marking in HTML report has issues

### ISSUE THREAD

**Issue by mydea** [kategengler/ember-cli-code-coverage#171]
In one of our apps, the marking in the HTML report has issues. We have the `useBabelInstrumenter` flag set to true.

It seems to not correctly take code like this into account: `let values = get(this, 'values') || [];` 
If the fallback part is not covered (e.g. the []), it will correctly mark it yellow, as "branch not covered". However, __everything__ after that will also be marked yellow. Not only in the function, but also all functions below that part.

I have this issues basically everywhere where I use this pattern.

A longer example:

```js
export default Component.extend({
  function1() {
    // do something
  },
  function2() {
    let values = get(this, 'values') || [];
    // do something else
  },
  function3() {
    // do something
  }
});
```

In the above example, everything starting with the `[]` would be marked yellow, including everything inside of `function3`.

I'm not sure if this is the correct place to create an issue - if not, it would be great if you could direct me to where I should report this. I _think_ it is related to `useBabelInstrumenter`, but cannot verify (since it doesn't even run without it activated).

**Comment by kategengler** [comment]
@mydea Can you try the beta of 1.0.0?

`useBabelInstrumenter` is gone in that version, replaced by https://github.com/istanbuljs/babel-plugin-istanbul If the issue persists with that, it should go to that repo.

**Comment by mydea** [comment]
Hey,

looks good to me in 1.0.0-beta.3! Thank you :)
