### ISSUE TITLE
`ember coverage-merge` caused the instanbul-reports issue

### ISSUE THREAD

**Issue by TigressBailey** [kategengler/ember-cli-code-coverage#174]
Hi,
The issue is
```cross-env COVERAGE=true ember exam --split=3 --parallel``` 
The result is perfect.

Then run```ember coverage-merge && rm -rf ./coverage_*```
![image](https://user-images.githubusercontent.com/15047538/38685907-a66952a2-3ea5-11e8-9dc1-aa44f106733e.png)

The `ember-cli-code-coverage` version is `v1.0.0-beta.3`
Can you please give a hint on this?

And another thing is the `instanbul-reports` are deprecated by instanbul.
https://github.com/istanbuljs-archived-repos/istanbul-reports
Do you consider to upgrade to `instanbuljs`?

**Comment by kategengler** [comment]
We have a dependency on the `istanbul-api` package, which as far as I can see is not deprecated, and uses the `istanbul-reports` package, also not deprecated (but was moved to the `istanbuljs` monorepo). We are on a slightly outdated version of `istanbul-api`, but it looks like the line that errored is the same in the latest version. 

Could you attempt to reproduce the problem in a clean ember app?

**Comment by TigressBailey** [comment]
@kategengler  Issues resolved by cleaning up the app folder. We've experienced this on the CI server so it was recognized just now.
Thanks for your comment!
