### ISSUE TITLE
COVERAGE=true adds extra test that fails on High Sierra

### ISSUE THREAD

**Issue by mariani-gg** [kategengler/ember-cli-code-coverage#176]
Using this package with High Sierra (10.13.3) seems to result in an additional test that fails, as well as incorrect test counts in the testem runner.  We have tested this with a machine using Sierra (10.12.6) and High Sierra (10.13.3), and the issue only presents itself on machines running High Sierra (10.13.3).  This issue manifests when using Firefox, Chrome, and headless Chrome.  We also get some error messages in the testem runner that only appear when using the COVERAGE flag.

Error Output:
```
Error: Browser timeout exceeded: 10s2018-04-13 13:19:32.005 Google Chrome[14180:181004] **
* Owner supplied to -[NSTrackingArea initWithRect:options:owner:userInfo:] referenced a de
allocating object. Tracking area behavior is undefined. Break on NSTrackingAreaDeallocatin
gOwnerError to debug.
```

```
2018-04-13 13:19:33.081 Google Chrome[14180:181004] Errors logged by ksadmin: KSKeyedPersi
stentStore store directory does not exist. [com.google.UpdateEngine.CommonErrorDomain:501 
- '/Library/Google/GoogleSoftwareUpdate/TicketStore' - 'KSKeyedPersistentStore.m:368']
```

Our testem.js file is as follows:
```
  module.exports = {
  test_page: 'tests/index.html?hidepassed',
  disable_watching: true,
  launch_in_ci: ['Chrome'],
  launch_in_dev: ['Chrome'],
  browser_args: {
    Chrome: {
      mode: 'ci',
      args: [
        // --no-sandbox is needed when running Chrome inside a container
        process.env.TRAVIS ? '--no-sandbox' : null,
        '--disable-gpu',
        '--headless',
        '--remote-debugging-port=0',
        '--window-size=1440,900',
      ].filter(Boolean),
    },
  },
};
```

Our relevant package dependencies are as follows: 
- ember-cli: ~3.0.2
- ember-cli-mocha: ^0.15.0
- ember-cli-babel: ^6.11.0
- ember-cli-chai: ^0.4.3
- ember-cli-code-coverage: 1.0.0-beta.3
- ember-native-dom-helpers: ^0.6.2

Our browser versions are as follows:
- Chrome: 65.0.3325.181
- Firefox: 59.0.2

**Comment by kategengler** [comment]
@mariani-gg Could you attempt to reproduce this in a new ember app that you can share? I use High Sierra myself and have never seen this.

**Comment by rwwagner90** [comment]
I've also never seen this, closing unless there is a reproduction available.
