### ISSUE TITLE
How to get text reporter input in console

### ISSUE THREAD

**Issue by chilicoder** [kategengler/ember-cli-code-coverage#178]
After running `COVERAGE=true ember test` I want to get coverage report in console
I tried to put text-summary reporter into configuration like this
```
module.exports = {
  reporters: ['text-summary']
};
```
without any success. 

Can you suggest me any approach? I didn't see in code any ways how to provide options to istanbul

**Comment by rwwagner90** [comment]
@chilicoder perhaps try `text` instead of `text-summary`? I am pretty sure that works or at least used to work.

**Comment by adamjmcgrath** [comment]
`'text-summary'` works for me. Are you getting any coverage data at all after running `COVERAGE=true ember test`? (check if you have a `coverage` folder)

> I tried to put text-summary reporter into configuration like this

Also, just double checking that you're putting your config in the correct place (`config/coverage.js`)

```
// config/coverage.js
module.exports = {
  reporters: ['text-summary']
};
```

**Comment by chilicoder** [comment]
I checked on a clean project and both `text` and `text-summary` work. Thanks for your answers, looks like its something with my app.
