### ISSUE TITLE
Coverage in Engines 

### ISSUE THREAD

**Issue by wojm** [kategengler/ember-cli-code-coverage#180]
I'm having trouble getting coverage in engines to work. This is specific to a private repo, but I've tried running coverage in this repo without success.

Steps to reproduce:
```
cd test/fixtures/my-app-with-in-repo-engine/
COVERAGE=true ember test
cd ../../..
vim coverage/coverage-summary.json 
```
This will show that there are a total of 0 lines in the report although all of the tests have been run. 

There is an active PR that seems related to this: 
 - https://github.com/kategengler/ember-cli-code-coverage/pull/103

Some past issues that seem related:
 - https://github.com/kategengler/ember-cli-code-coverage/issues/86 this asked to allow for coverage of in-repo addons. This led to the above test that did not show coverage of lines in the in-repo addon

As a followup for my specific scenario: my `app/` folder and `/lib` folder (lib contains all my engines) are on the same level. When I move the lib folder into the app folder, coverage works fine

**Comment by rwwagner90** [comment]
@wojm this seems odd. We have test cases that check that in-repo engines work. Can you share your versions of `ember-cli-code-coverage`, `ember-cli`, `engines`, etc?

**Comment by rwwagner90** [comment]
Yes, updating should fix the issues.
