### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ming-codes** [kategengler/ember-cli-code-coverage#181]
https://github.com/kategengler/ember-cli-code-coverage/blob/ca8ffbb9f3f2864e21dc53bfa5241b1ad3941529/lib/attach-middleware.js#L22

Somehow the passed in `fileLookup` is null.

I did some investigation. `include` hook is indeed called before `serverMiddleware`, but the `this.fileLookup` in `serverMiddleware` is not the same instance as the one in `include`.

This is on `ember-cli-code-coverage@1.0.0-beta.4`

**Comment by ming-codes** [comment]
🤔 Even `this` context is different between `included` and `serverMiddleware` hooks.

**Comment by rwwagner90** [comment]
@ming-codes do you have a reproduction we could look at? Coverage is working for me.
