### ISSUE TITLE
COVERAGE=true ember server

### ISSUE THREAD

**Issue by SantoshRaoBlr** [kategengler/ember-cli-code-coverage#183]
I have a situation like this, where I have set of tests written in Cucumber running against the ember application. Is there a way I could possibly run the coverage tool instead of using ember tests, and run the app using ember server and separately run the cucumber tests, and check out the coverage results separately.

**Comment by rwwagner90** [comment]
This is built to use with Ember tests, I don't think it will work with cucumber.

**Comment by SantoshRaoBlr** [comment]
Yes, I saw that, but I was wondering, it may be nice to introduce at some time, to just generate a coverage report from a running instance.
