### ISSUE TITLE
Coverage Report in VSTS not using external CSS

### ISSUE THREAD

**Issue by jrock2004** [kategengler/ember-cli-code-coverage#185]
So looking at the following screenshot, the nice CSS formatting you guys do get lost in VSTS as it seems like VSTS rips them out. Any thoughts of adding a variable or something to inline those 2 CSS files? Thanks

![image](https://user-images.githubusercontent.com/655716/41621090-ac600c50-73d9-11e8-9596-47cf2aa73b70.png)

**Comment by rwwagner90** [comment]
I'm pretty sure the CSS is just built into Istanbul, right @kategengler?

**Comment by jrock2004** [comment]
@rwwagner90 Yeah that is what I noticed looking over the code. Right now I am playing around with using `gulp` and `gulp-inline-source` to see if I can do that to get this to work. Hate that I would have to add gulp just for this.

**Comment by jrock2004** [comment]
Opening issue over at istanbul https://github.com/gotwarlost/istanbul/issues/890

**Comment by jrock2004** [comment]
Wait is that the place to open it

**Comment by rwwagner90** [comment]
@jrock2004 what is VSTS? I would think they just need to support Istanbul.

**Comment by jrock2004** [comment]
@rwwagner90 it’s Visual Studio Team Services. The problem is they strip out links to external css and js files. It needs to be inline

**Comment by rwwagner90** [comment]
@jrock2004 right, so the issue is VSTS. They need to not do that. I would open a bug with them.
