### ISSUE TITLE
Usage on windows.

### ISSUE THREAD

**Issue by Straightline** [kategengler/ember-cli-code-coverage#187]
When I run `COVERAGE=true ember test` that doesn't work on windows, so I tried to `ember test COVERAGE=true` which also does nothing. So how do you use this on windows?

I know it's installed as it's visible in the node_modules folder.

ember-cli-code-coverage: 0.4.2
ember-cli: 3.2.0

**Comment by rwwagner90** [comment]
@Straightline please try the latest beta 1.0.0-beta.4

**Comment by Straightline** [comment]
I stayed using 0.4.2 and got it working, so thank you anyways!
