### ISSUE TITLE
Not working with ember-cli-babel@^7.1.0

### ISSUE THREAD

**Issue by scottkidder** [kategengler/ember-cli-code-coverage#189]
I just noticed our coverage has been reporting as 100% 0/0 lines. It appears this all started when our projects upgraded to ember-cli-babel@^7.1.0 from ember-cli-babel@^6.17.0

**Comment by rwwagner90** [comment]
@adamjmcgrath any ideas on this? I don't have a ton of time to investigate this right now.

**Comment by scottkidder** [comment]
@rwwagner90 I made a minimal reproduction repo [here](https://github.com/scottkidder/ec-no-cov)

**Comment by adamjmcgrath** [comment]
This has been fixed in `babel-plugin-istanbul@5.1.0` - it's just not been release yet

As a workaround you can do `npm install babel-plugin-istanbul@next`

**Comment by rwwagner90** [comment]
@adamjmcgrath do you know why this would still be broken?

**Comment by adamjmcgrath** [comment]
Ah ok, it still looks like an issue with `babel-plugin-istanbul`, babel 7 now sets `opts.filename` to an absolute path (https://github.com/babel/babel/pull/8044), so it needs to change to a relative (module) path - similar to the fix in https://github.com/babel/ember-cli-babel/pull/234/files#diff-168726dbe96b3ce427e7fedce31bb0bcR26

**Comment by rwwagner90** [comment]
@adamjmcgrath is there a way we can support both babel 6 and 7 or are we forced to choose here?

**Comment by rwwagner90** [comment]
@adamjmcgrath @kategengler can/should we be supporting both babel 6 and 7 or should we just support 7+ in 1.0+ of this lib?

**Comment by adamjmcgrath** [comment]
The latest ember-cli blueprints still use babel 6 (https://github.com/ember-cli/ember-cli/blob/v3.5.0-beta.1/blueprints/app/files/package.json#L27) so I think it will be a while before most users are on 7

**Comment by rwwagner90** [comment]
@adamjmcgrath While this is true, we want to make sure we either support both for awhile or cut support for babel 6, I think.
