### ISSUE TITLE
Support for module unification app

### ISSUE THREAD

**Issue by abhilashlr** [kategengler/ember-cli-code-coverage#197]
The current stable 0.4.2 or the beta (6) version do not have support for module unification app layout. However, there is a fix for this in the current stable version:
https://github.com/kategengler/ember-cli-code-coverage/compare/v0.4.2...abhilashlr:v0.4.2-module-unification

Would like to know what is the plan with respect to this MU support.?

**Comment by rwwagner90** [comment]
@abhilashlr we'll need to support it for sure. If you have a solution, please submit a PR 😃

**Comment by abhilashlr** [comment]
But I am unable to send a PR against the tag, can you please publish the 0.4.2 tag as a branch? I can then send a PR.
At the moment, there are couple of issues with respect to this diff:
- [ ] the coverage is run for *-test.js files inside the src directory; and 
- [ ] the tests are run twice.

**Comment by rwwagner90** [comment]
@abhilashlr we would want these changes in the new code, not in the 0.4.2 code. Can you make these changes based on the master branch?

**Comment by abhilashlr** [comment]
Okay. I can try.

**Comment by abhilashlr** [comment]
@rwwagner90 Can you please review the PR.

**Comment by rwwagner90** [comment]
Closing since MU is dead.
