### ISSUE TITLE
Support older testem and /tests for mocha users

### ISSUE THREAD

**Issue by kategengler** [kategengler/ember-cli-code-coverage#2]
Assuming Mocha has a similar hook, this can be done similarly to support for QUnit for older testem or `/tests` users as done here https://github.com/kategengler/ember-cli-code-coverage/blob/master/lib/templates/test-body-footer.html#L42

Main blocker to adding this is not having an app that uses Mocha for ember tests.

**Comment by Turbo87** [comment]
@kategengler https://github.com/TryGhost/Ghost-Admin is using `ember-cli-mocha` if that is still relevant

**Comment by rwwagner90** [comment]
@kategengler do we still need to support this?

**Comment by kategengler** [comment]
Seems like it was fixed by #119
