### ISSUE TITLE
How do I get coverage from the /tests endpoint when running ember s?

### ISSUE THREAD

**Issue by NullVoxPopuli** [kategengler/ember-cli-code-coverage#204]
I'd like to be able to have tests constantly run as I'm writing them and coverage constantly generated as I'm working on my tests.

Is there a way to do this?

**Comment by rwwagner90** [comment]
As far as I know, there is not a way to constantly generate coverage, but I don't know much about Istanbul.

**Comment by allthesignals** [comment]
Wondering if you discovered anything new on this front, @NullVoxPopuli - I am also curious about configuring coverage as a CI check for Github.

**Comment by NullVoxPopuli** [comment]
I haven't made any progress. I still have highlighting / alignment issues.

**Comment by rwwagner90** [comment]
@allthesignals a coverage check can be done a few ways. I use Code Climate for that. Feel free to ping me on discord if you need help setting something up.

**Comment by rwwagner90** [comment]
@kategengler with that in mind, we should close this right?

**Comment by kategengler** [comment]
Assuming what I said works is working for @NullVoxPopuli

**Comment by NullVoxPopuli** [comment]
I'll check in a bit!

**Comment by NullVoxPopuli** [comment]
yup!
