### ISSUE TITLE
Coverage report created, but reported as 0%

### ISSUE THREAD

**Issue by jnfingerle** [kategengler/ember-cli-code-coverage#207]
Hello,

for some reason, I still get coverage reports, but coverage ist reported as 0%. I've created a minimal test case as follows:

```
T:\>ember --version
ember-cli: 3.4.3
node: 8.11.4
os: win32 x64

T:\>ember new test-coverage --yarn
installing app
[...]

T:\>cd test-coverage

T:\test-coverage>ember install ember-cli-code-coverage@1.0.0-beta.7
Yarn: Installed ember-cli-code-coverage@1.0.0-beta.7
Installed addon package.

T:\test-coverage>ember g component test-component
installing component
  create app\components\test-component.js
  create app\templates\components\test-component.hbs
installing component-test
  create tests\integration\components\test-component-test.js

T:\test-coverage>"C:\Program Files (x86)\Notepad++\notepad++.exe" app\components\test-component.js
[editing]

T:\test-coverage>type app\components\test-component.js
import Component from '@ember/component';

export default Component.extend({
  init() {
    // some code, that should be found be ember-cli-code-coverage
    this._super(...arguments);
  }
});

T:\test-coverage>set COVERAGE=true


T:\test-coverage>ember test
Environment: test
cleaning up...
Built project successfully. Stored in "T:\test-coverage\tmp\class-tests_dist-Jnusd976.tmp".
ok 1 Chrome 70.0 - [254 ms] - Integration | Component | test-component: it renders
ok 2 Chrome 70.0 - [0 ms] - ESLint | app: app.js
ok 3 Chrome 70.0 - [0 ms] - ESLint | app: components/test-component.js
ok 4 Chrome 70.0 - [1 ms] - ESLint | app: resolver.js
ok 5 Chrome 70.0 - [0 ms] - ESLint | app: router.js
ok 6 Chrome 70.0 - [1 ms] - TemplateLint: test-coverage/templates/application.hbs
ok 7 Chrome 70.0 - [0 ms] - TemplateLint: test-coverage/templates/components/test-component.hbs
ok 8 Chrome 70.0 - [0 ms] - ESLint | tests: integration/components/test-component-test.js
ok 9 Chrome 70.0 - [0 ms] - ESLint | tests: test-helper.js
ok 10 Chrome 70.0 - [0 ms] - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly

1..10
# tests 10
# pass  10
# skip  0
# fail  0

# ok

T:\test-coverage>
```

The resulting project can be found at https://github.com/jnfingerle/ember-project-zero-coverage.

The resulting lcov.info is 
```
TN:
SF:app\app.js
FNF:0
FNH:0
LF:0
LH:0
BRF:0
BRH:0
end_of_record
TN:
SF:app\resolver.js
FNF:0
FNH:0
LF:0
LH:0
BRF:0
BRH:0
end_of_record
TN:
SF:app\router.js
FNF:0
FNH:0
LF:0
LH:0
BRF:0
BRH:0
end_of_record
TN:
SF:app\components\test-component.js
FNF:0
FNH:0
LF:0
LH:0
BRF:0
BRH:0
end_of_record
```

coverage-summary.json is at 0% coverage as well.

**Comment by jnfingerle** [comment]
I've just tested this with ember 3.6, the result is still the same.

**Comment by nfc036** [comment]
I'm facing the same problem and it seems to be Windows related.

`walkSync` yields entries with keys like 'appname/controllers/application.js' (slash as directory separator).
https://github.com/kategengler/ember-cli-code-coverage/blob/012463c429d6821d355b8672a81315d0ebe9f330/index.js#L203-L207


This is later used in function `writeCoverage` as `fileLookup` to map the coverage results to the corresponding filenames
https://github.com/kategengler/ember-cli-code-coverage/blob/012463c429d6821d355b8672a81315d0ebe9f330/lib/attach-middleware.js#L29-L32

BUT, the coverage results are coming in with a backslash as directory separator. `fixedCoverage` generated here 
https://github.com/kategengler/ember-cli-code-coverage/blob/012463c429d6821d355b8672a81315d0ebe9f330/lib/attach-middleware.js#L24-L28 
contains (on Windows) entries with keys like 'appname\\controllers\\application.js' that do not match `filename` in this line 
https://github.com/kategengler/ember-cli-code-coverage/blob/012463c429d6821d355b8672a81315d0ebe9f330/lib/attach-middleware.js#L30

I am not sure, **where** and **how** this could be fixed, but changing line 
https://github.com/kategengler/ember-cli-code-coverage/blob/012463c429d6821d355b8672a81315d0ebe9f330/lib/attach-middleware.js#L25
to
```
    const modulePath = path.relative(root, filePath).replace(/\\/g, '/');
```
seems to fix this issue.

**Comment by rwwagner90** [comment]
@adamjmcgrath any ideas on this?

**Comment by adamjmcgrath** [comment]
I don't have a windows machine to test this on but if https://github.com/kategengler/ember-cli-code-coverage/issues/207#issuecomment-448279446 is true, #208 should fix the issue

**Comment by rwwagner90** [comment]
@nfc036 @jnfingerle I just merged the PR from @adamjmcgrath. Can you guys try using the master branch please? I also do not have a Windows machine to test on.

**Comment by nfc036** [comment]
No, sorry. `root` is i.e. C:\appname\frontend, `filePath` is i.e. C:\appname\frontend\controllers\application.js and then  `modulePath` becomes ../C:\appname\frontend\controllers\application.js.

**Comment by rwwagner90** [comment]
@adamjmcgrath are you following what @nfc036 is saying?

**Comment by nfc036** [comment]
From my point of view, #208 should be reverted. 

As noted above, 
```const modulePath = path.relative(root, filePath).replace(/\\/g, '/');``` 
gives also on Windows non-empty coverage results as expected... There is a node package "slash" that could be used as well and that is basically doing the very same replace...

**Comment by nfc036** [comment]
@adamjmcgrath How about this snippet? (The replace above could give problems on Posix with filenames containing backslashes.)
```
    const modulePath = path.relative(root, filePath).split(path.sep).join('/');
```

**Comment by adamjmcgrath** [comment]
@jnfingerle or @nfc036 can you confirm that https://github.com/kategengler/ember-cli-code-coverage/tree/adamjmcgrath-patch-2-1 works for you?

**Comment by jnfingerle** [comment]
> 
> 
> @jnfingerle or @nfc036 can you confirm that https://github.com/kategengler/ember-cli-code-coverage/tree/adamjmcgrath-patch-2-1 works for you?

@adamjmcgrath I can confirm that it works for me.

**Comment by rwwagner90** [comment]
Merged the fix to master. Thanks @adamjmcgrath!

**Comment by srini88** [comment]
@rwwagner90 when can we expect a new release `v1.0.0-beta.8` with this fix?

**Comment by rwwagner90** [comment]
@srini88 Travis is supposed to publish it, but it is having issues. I just manually published it for now.

**Comment by TheLooseCannon** [comment]
im currently running on 1.0.0-beta.9 and i too am getting 0% as output.
what all might be going wrong?
