### ISSUE TITLE
No Coverage generated got following error

### ISSUE THREAD

**Issue by akhileshk** [kategengler/ember-cli-code-coverage#21]
After ember-cli-code-coverage used following command  "COVERAGE=true ember test" to run the test
getting following error:

{ type: 'error',
              text: 'Error: Pretender intercepted POST /write-coverage but no handler was defined for this type of request at http://localhost:7357/assets/vendor.js, line 68809\n' }

Do I need to do any configuration on my end?

//env:    
Package.json
 "devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.5.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-code-coverage": "0.2.2",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-pretender": "0.6.0",
    "ember-cli-qunit": "^1.1.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.0.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-load-initializers": "0.5.1",
    "ember-resolver": "^2.0.3",
    "loader.js": "4.0.10"
  }
Bower.json:
  "dependencies": {
    "ember": "2.5.0",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-load-initializers": "0.1.7",
    "ember-qunit-notifications": "0.1.0",
    "jquery": "1.11.3",
    "loader.js": "^3.5.0",
    "qunit": "~1.20.0",
    "pretender": "^0.12.0",
    "bootstrap": "3.1.1",
    "moment": "~2.11.1",
    "markdown": "~0.5.0",
    "bootstrap-tokenfield": "~0.12.1"
  },

**Comment by benoror** [comment]
@akhileshk https://github.com/kategengler/ember-cli-code-coverage/#using-when-intercepting-all-ajax-requests-in-tests

**Comment by akhileshk** [comment]
@benoror 
Could you pls. elaborate?  I am little new to Ember.js
I have seen this section and, I am already using a pretender which has the required fix("pretender": "^0.12.0",).  I am not using the mirage, do I suppose to provide a post method and write the coverage data myself?

I have fake-server.js which mock all the server data thru pretender if I provide following post method in fake-server.js, I do get  data in this post call
Ex.
this.post('/write-coverage', function(req){
}
request in he above function call looks like this, 

{ type: 'log',  text: '{ _eventListeners: \n   
{ loadend: [ null ],\n     abort: [ null ],\n     load: [ null ],\n     progress: [ null ],\n     loadstart: [ null ] },\n  
readyState: 1,\n  
requestHeaders: \n   { \'Content-Type\': \'application/json; charset=utf-8\',\n     Accept: \'*/*\',\n     \'X-Requested-With\': \'XMLHttpRequest\' },\n  
requestBody: \'{"app/fake-server.js":{"path":"app/fake-server.js","s":{"1":1,"2":0,"3":1,"4":0,"5

**Comment by akhileshk** [comment]
I tried with a different Ember App which uses pretender and Mirage and it does generate a coverage report. 
With the Istanbul, one can instrument the code base and run the test latter on the instrumented code, can we do some thing similar with this plugin for ember app. 
The document does mentioned that :
"it instruments your application code as part of the build, when enabled."
so how do we enable code instrumentation during ember build?

**Comment by kategengler** [comment]
`COVERAGE=true` is the part that enables instrumentation of the code. You have that in the command you ran.
