### ISSUE TITLE
Long instrumentation phase?

### ISSUE THREAD

**Issue by veelenga** [kategengler/ember-cli-code-coverage#230]
We have a big ember app and it looks like coverage becomes a bottleneck for our production builds. For some reason, it takes a very long time to build the app when coverage is enabled. Can be reproduced locally too:

```
$ time COVERAGE=true ember exam --split=4 --partition=1 --parallel --filter="..."
289.85s user 28.18s system 126% cpu 4:10.86 total

$ time ember exam --split=4 --partition=1 --parallel --filter="..."
55.71s user 19.37s system 115% cpu 1:05.22 total
```

As you can see the diff is 3 minutes (75% of time). A very similar relative diff is on CI. 

```js
// config/coverage.js
module.exports = {
  useBabelInstrumenter: true,
  parallel: true
};

```

We tried to exclude everything except `app` folder, but it looks like this is default behavior and doesn't give any effect.  

Can you suggest what to do in order to improve the timing?

**Comment by kategengler** [comment]
This addon delegates to https://github.com/istanbuljs/babel-plugin-istanbul for instrumentation, and it is a layer atop that for Ember apps. I suggest looking into what the times are directly using that.

To me, it is not unexpected that a large app will take a long time to instrument, it is literally wrapping every line of code.
