### ISSUE TITLE
Request to publish latest tag version of ember-cli-code-coverage

### ISSUE THREAD

**Issue by axelerate** [kategengler/ember-cli-code-coverage#240]
The latest code changes resolves ongoing issues when it comes to generating correct reports for our Ember addons.

**Comment by mehulkar** [comment]
What are the blockers for releasing 1.0 (not beta)?

**Comment by axelerate** [comment]
@kategengler Any blockers for release v1.0.0?

**Comment by narayanpai** [comment]
@rwjblue Any updates on when the latest version can be released?

**Comment by kategengler** [comment]
If anybody has time, before the next release I'd like to verify that the README and options presented in there are correct and working for the latest beta. Any volunteers?

**Comment by axelerate** [comment]
I'll volunteer. Will post results.

**Comment by rwwagner90** [comment]
@mehulkar there is an issue with things we need to do before 1.0.0 https://github.com/kategengler/ember-cli-code-coverage/issues/152

Plus I think there are concerns around the ever changing Ember build process, and that there may be a total rewrite of this addon at some point. @kategengler would know more about this and her plans for the future of this addon.

**Comment by rwwagner90** [comment]
1.0.0-beta.9 has been published. Hopefully we can get an actual 1.0.0 out soon! I believe 0.4.2 doesn't work with modern Ember, and 1.0.0 has been in beta a long time, so my vote would be to go ahead and publish.

**Comment by axelerate** [comment]
Thanks @rwwagner90 ! I see you've modified the version name, but I'm not seeing the version tag for 1.0.0-beta.9 being published. Am I missing something?

**Comment by kategengler** [comment]
@axelerate Thanks for taking that on. Looking forward to hearing your results. 

fwiw, @rwwagner90, I personally use 0.4.2 with modern ember and have had no difficulties. It's one of the things that concerns me -- some combination of circumstances makes it not work for only some people.

**Comment by rwwagner90** [comment]
@kategengler what's your project like? I hit several things, like I think there was first an issue with babel 6 or 7 updates, some things with glimmer 2 and now glimmer.js etc. I don't 100% know, but I think there are a lot of things incompatible with 0.4.2 and I have been using the 1.0.0 betas for years across multiple different organizations with varying setups, and had no issues, so I think the beta has proved it's working.

**Comment by rajasegar** [comment]
@kategengler v0.4.2 doesn't work with modern Ember. I am using ember 3.17

**Comment by rwwagner90** [comment]
@rajasegar please use 1.0.0-beta.9

**Comment by rajasegar** [comment]
@rwwagner90 Thanks a lot, that worked.

**Comment by rwwagner90** [comment]
@axelerate did you get a chance to verify the README? I would love to get 1.0.0 stable out, since it has been in beta for many years.

**Comment by rwjblue** [comment]
https://github.com/kategengler/ember-cli-code-coverage/releases/tag/v1.0.0
