### ISSUE TITLE
Typescript issue

### ISSUE THREAD

**Issue by yratanov** [kategengler/ember-cli-code-coverage#241]
I'm using `"ember-cli-code-coverage": "^1.0.0-beta.8"`

And typescript code coverage doesn't work. Please see the repo: https://github.com/yratanov/ember-page-object-asserts

Am I doing something wrong?

**Comment by lifeart** [comment]
@yratanov check this branch: https://github.com/kategengler/ember-cli-code-coverage/pull/223

**Comment by yratanov** [comment]
@lifeart Yes, I saw it. I thought it should be in `1.0.0-beta.8`?

**Comment by lifeart** [comment]
@yratanov nope, use gh commit in package.json

beta 8 - 1 year old

**Comment by yratanov** [comment]
@lifeart thank you. Closing it
