### ISSUE TITLE
Latest master commit fails with this._getIncludesForAddonDirectory is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by NullVoxPopuli** [kategengler/ember-cli-code-coverage#265]
in my package.json, I have: 
```
    "ember-cli-code-coverage": "github:kategengler/ember-cli-code-coverage",
```

I had recently obliterated my lockfile and re-installed deps while debugging another issue, and ran in to this

<details>
<summary>Error Log</summary>
ENV Summary:

  TIME: Fri Jun 05 2020 07:06:46 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/bin/node
  - /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/.bin/ember
  - exam
  - --random
  EXEC_PATH: /home/preston/.volta/tools/image/node/14.3.0/6.14.5/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /tmp/yarn--1591355202367-0.7585613598798653
  - /home/preston/Development/NullVoxpopuli/emberclear/client/web/emberclear/node_modules/.bin
  - /home/preston/.config/yarn/link/node_modules/.bin
  - /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/.bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/lib/node_modules/npm/bin/node-gyp-bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/bin/node_modules/npm/bin/node-gyp-bin
  - /tmp/yarn--1591355202061-0.41218556990858435
  - /home/preston/Development/NullVoxpopuli/emberclear/client/web/emberclear/node_modules/.bin
  - /home/preston/.config/yarn/link/node_modules/.bin
  - /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/.bin
  - /home/preston/.yarn/bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/lib/node_modules/npm/bin/node-gyp-bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/bin/node_modules/npm/bin/node-gyp-bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/bin
  - /home/preston/.volta/tools/image/yarn/1.22.4/bin
  - /home/preston/.pythons/Python-3.6.3/bin
  - /home/preston/.cargo/bin
  - /home/preston/Applications
  - /home/preston/apps/phantomjs/bin
  - /home/preston/scripts/system-utils
  - /home/preston/scripts/git
  - /home/preston/scripts/rails
  - /home/preston/scripts
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /home/preston/.fzf/bin
  PLATFORM: linux x64
  FREEMEM: 4162699264
  TOTALMEM: 20497272832
  UPTIME: 644309
  LOADAVG: 1.28759765625,1.0029296875,0.8662109375
  CPUS:
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.0
  - brotli: 1.0.7
  - cldr: 37.0
  - icu: 67.1
  - llhttp: 2.0.4
  - modules: 83
  - napi: 6
  - nghttp2: 1.40.0
  - node: 14.3.0
  - openssl: 1.1.1g
  - tz: 2019c
  - unicode: 13.0
  - uv: 1.37.0
  - v8: 8.1.307.31-node.33
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: this._getIncludesForAddonDirectory is not a function or its return value is not iterable
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: this._getIncludesForAddonDirectory is not a function or its return value is not iterable
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: this._getIncludesForAddonDirectory is not a function or its return value is not iterable
    at Class._getIncludes (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/ember-cli-code-coverage/index.js:132:15)
    at Class.included (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/ember-cli-code-coverage/index.js:45:30)
    at Class.superWrapper [as included] (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/core-object/lib/assign-properties.js:34:20)
    at /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/ember-cli/lib/broccoli/ember-app.js:632:15
    at Array.forEach (<anonymous>:null:null)
    at EmberApp._notifyAddonIncluded (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/ember-cli/lib/broccoli/ember-app.js:630:25)
    at new EmberApp (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/ember-cli/lib/broccoli/ember-app.js:138:10)
    at module.exports (/home/preston/Development/NullVoxpopuli/emberclear/client/web/emberclear/ember-cli-build.js:39:13)
    at Builder.readBuildFile (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/ember-cli/lib/models/builder.js:29:10)
    at BuildTask.run (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/ember-cli/lib/tasks/build.js:13:19)
    at /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/ember-cli/lib/models/command.js:238:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

</details>

Downgrading to 1.0.0-beta.9 appears to make this error go away :shrug:

**Comment by NullVoxPopuli** [comment]
Just tried running tests without `COVERAGE=true`, and my tests started running, so that means that this is relevant / maybe _caused by_ (?) ec-code-coverage? https://github.com/babel/ember-cli-babel/issues/350

**Comment by rwjblue** [comment]
This is being tracked over in ember-cli/babel-plugin-ember-modules-api-polyfill#112. I'll leave this issue open while we work things through (to make it easier to find that issue), but lets focus the convo over there.

**Comment by Turbo87** [comment]
resolved by https://github.com/kategengler/ember-cli-code-coverage/commit/7cea2b652f3e70ba9a84d93ecdb78a102b424ca6
