### ISSUE TITLE
[INFORMATION] Should use official release of beta versions?

### ISSUE THREAD

**Issue by rogeraraujo90** [kategengler/ember-cli-code-coverage#268]
Hello!

I saw that the latest oficial release is too old (2017). And there are a lot of beta tags in this repository.

What the recommendation of the maintainers about use this add-on in an already in production and big Ember App? Run `ember install ember-cli-code-coverage` (will install the 0.4.2 version) or add the latest available tag?

**Comment by rwjblue** [comment]
Right now you _basically_ have to use the beta for all practical purposes. I am working through some failures introduced on master (#265 and https://github.com/kategengler/ember-cli-code-coverage/pull/264), but once resolved that should allow us to release the next stable (non-beta) version.

**Comment by rogeraraujo90** [comment]
Good. Thank you!
