### ISSUE TITLE
ember-exam generates empty reports when given a path to existing build and running parallel tests

### ISSUE THREAD

**Issue by GCheung55** [kategengler/ember-cli-code-coverage#271]
Instrumenting a build and running ember-exam with parallel tests and a path to the build generates empty reports.

Reproduction steps:
1. Instrument a build.
```bash
COVERAGE=true ember build
```

2. Execute parallel tests with path to existing instrumented build from step 1. Note the default build is put in `./dist`.
```bash
COVERAGE=true ember exam --split=8 --parallel=1 --path=./dist
```

Expected:
`coverage_<hash>/lcov.info` files have data.

Actual:
`coverage_<hash>/lcov.info` files are empty.

**Comment by rwwagner90** [comment]
@GCheung55 @GCheung55 I believer running with `--path` in general is broken. There was a fix added here https://github.com/kategengler/ember-cli-code-coverage/pull/248 but we have not released a new beta because things are somewhat broken right now.

**Comment by GCheung55** [comment]
@rwwagner90 what needs to be fixed before a new release?

**Comment by kategengler** [comment]
This needs to be completed https://github.com/kategengler/ember-cli-code-coverage/pull/264

**Comment by GCheung55** [comment]
Looks like #293 fixes the issue. @kategengler @rwwagner90, anything I can do to help get the PR merged and a new release published?
