### ISSUE TITLE
Container is falsy build error with coverage enabled

### ISSUE THREAD

**Issue by Samsinite** [kategengler/ember-cli-code-coverage#283]
Hi, thanks for the addon!

I'm on 1.0.0, using ember/ember-cli 3.20 (this was not an issue with ember-cli 3.16), and am getting a weird build error with coverage enable:
```
Build Error (broccoli-persistent-filter:Babel > [Babel: app-ember]) in app-ember/controllers/roles/attorneys.js

/Users/samueljclopton/workspace/clever-case/app-ember/app-ember/controllers/roles/attorneys.js: Container is falsy
```

This file is actually at `/Users/samueljclopton/workspace/clever-case/app-ember/controllers/roles/attorneys.js` so it appears that the coverage tool is messing up the file path.

The test build works fine with coverage disabled. Had the same error as well using the previous beta.

**Comment by rwjblue** [comment]
Some more details over in https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/issues/112 (the actual issue is somewhere between that babel plugin and the istanbul one).

**Comment by rreckonerr** [comment]
Reporting the same issue.
Any workarounds as a temporary solution?

**Comment by kevvvnguyen** [comment]
Hey all, was wondering if there have been any updates on this issue?

**Comment by UkonnRa** [comment]
+1

**Comment by rwjblue** [comment]
The issue was fixed in the downstream babel plugin (https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/156). Make sure you update to the latest version of that plugin, and you should be good to go.
