### ISSUE TITLE
Zero percent code coverage

### ISSUE THREAD

**Issue by rreckonerr** [kategengler/ember-cli-code-coverage#284]
Some of my components have 0% code coverage, even though integration tests are present.

**Component**
```js
import classic from "ember-classic-decorator";
import { classNames } from "@ember-decorators/component";
import TextField from "@ember/component/text-field";

@classic
@classNames("string-input")
export default class StringInput extends TextField {}
```
**Test**
```js
module("Integration | Component | string input", function(hooks) {
  setupRenderingTest(hooks);

  test("renders", async function(assert) {
    await render(hbs`{{string-input}}`);
    assert.dom(".string-input").exists();
  });

  test("renders a text input field", async function(assert) {
    await render(hbs`{{string-input}}`);
    assert.dom('input[type="text"]').exists();
  });

  test("renders the passed in value", async function(assert) {
    this.set("foo", "bar");
    await render(hbs`{{string-input value=foo}}`);
    assert.dom('input[type="text"]').hasValue("bar");
  });

  test("changes the passed in variable", async function(assert) {
    this.set("foo", "bar");
    await render(hbs`{{string-input value=foo}}`);
    await fillIn("input", "baz");
    await blur("input");
    assert.deepEqual(this.foo, "baz");
  });
});
```

What might be causing it? Code like `export default class BlablaService extends MyService {}` also has 0% code coverage, even though `MyService` is 100% covered.

**Comment by rwwagner90** [comment]
@rreckonerr what version of ember-cli-code-coverage are you using?

@Turbo87 @lifeart could this be related to removing some of the TypeScript stuff? IIRC TS and native classes were handled in a similar way?

**Comment by Turbo87** [comment]
I think the main issue here is that there are no statements in this file that would be instrumented by istanbul. I guess the export might technically be a statement, but apparently not according to what istanbul does. I'd say this behaves as intended from our side.

**Comment by rreckonerr** [comment]
@rwwagner90 Currently, I'm on `1.0.0-beta.9` and I'm receiving the same result on `1.0.0`.
@Turbo87 Thanks!
