### ISSUE TITLE
README not easily discoverable in v1.0.1 and v1.0.2

### ISSUE THREAD

**Issue by ijlee2** [kategengler/ember-cli-code-coverage#300]
## Description

Hello. I wanted to learn how to install and configure `ember-cli-code-coverage` today. I noticed that the `master` branch did not contain the README file in the root folder, and ended up switching to the `v1.0.0` tag to find the README.

It seemed like the project structure might have changed in `v1.0.1`. I was wondering if it can be still possible to have a README in the root folder so that visitors can easily find it. The README in the root folder could be a verbatim copy or display a link to the README in `packages/ember-cli-code-coverage`.

Another option may be to add the link to README under the About section?

<img width="400" alt="About section in GitHub repo site" src="https://user-images.githubusercontent.com/16869656/102362416-f8a3a900-3f79-11eb-83a0-30e575025a14.png">

**Comment by kategengler** [comment]
I think the README should be moved top level and it was just missed in the reorganization. 

@rwjblue Can you think of any reason not to do that?

**Comment by chrisvdp** [comment]
@ijlee2 @kategengler we can close this now.

**Comment by ijlee2** [comment]
@chrisvdp Thank you for your help!
