### ISSUE TITLE
reporters config via cli

### ISSUE THREAD

**Issue by tamdilip** [kategengler/ember-cli-code-coverage#305]
Can we have an option to pass reporter formats via CLI, apart from the placement of "coverage.js" under config path ?

**Comment by mukilane** [comment]
You could have something like this in coverage.js

```js
module.exports = {
  reporters: process.env.MY_CUSTOM_REPORTERS.split(' ')
};
```

and pass the values as an environment variable.

```bash
COVERAGE=true MY_CUSTOM_REPORTERS="html lcov text" ember test
```

**Comment by tamdilip** [comment]
> You could have something like this in coverage.js
> 
> ```js
> module.exports = {
>   reporters: process.env.MY_CUSTOM_REPORTERS.split(' ')
> };
> ```
> 
> and pass the values as an environment variable.
> 
> ```shell
> COVERAGE=true MY_CUSTOM_REPORTERS="html lcov text" ember test
> ```

Cool, great perspective to give that way of thought🔥✌️ !!
