### ISSUE TITLE
Not compatible with babel 7

### ISSUE THREAD

**Issue by daituzhang** [kategengler/ember-cli-code-coverage#317]
Same issue as https://github.com/kategengler/ember-cli-code-coverage/issues/215?_pjax=%23js-repo-pjax-container#issuecomment-831458285

ember-cli-code-coverage 1.0.2

Build Error (Analyzer)

Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

Stack Trace and Error Report: C:\Users\D621789\AppData\Local\Temp/error.dump.9e71015a0e76668fbf5e07f7a6ca8d20.log

**Comment by kategengler** [comment]
Can you try `yarn why ember-cli-babel` or `npm ls ember-cli-babel`. 

This addon is using babel 7 in test/dev. I would read the message as saying Babel 6.26.3 was being used when it should have been 7, but I expect that's not from this addon.

**Comment by daituzhang** [comment]
You are right. I will close the issue.

> Can you try `yarn why ember-cli-babel` or `npm ls ember-cli-babel`.
> 
> This addon is using babel 7 in test/dev. I would read the message as saying Babel 6.26.3 was being used when it should have been 7, but I expect that's not from this addon.
