### ISSUE TITLE
Dramatic build slowdown when enabled

### ISSUE THREAD

**Issue by mshappe** [kategengler/ember-cli-code-coverage#354]
When building (either separately, or inline as part of `ember exam`) with `COVERAGE=true`, builds take 2.5-3x as long. 

In practical terms, on SemaphoreCI this results in a 2-3 minute build becoming an 8-9 minute build, before tests are even run.

Even on my superfast M1, I got these timings:
With: 4:27.11 total
Without: 1:20.66 total

Obviously, instrumenting code for coverage is going to take **some** time, but this seems like too much!

**Comment by mshappe** [comment]
I will note that we wound up trying the 2.0.0-beta, and it does improve the situation significantly. This report was made against the 1.0.3 release.

**Comment by acorncom** [comment]
@mshappe if 2.0.0-beta works for you, then maybe we should close this issue? 2.x is the new future here once we get a final release out the door ...

**Comment by mshappe** [comment]
Yes, I think at this point, we can close this.
