### ISSUE TITLE
Addon Support: Properly name files in `lcov.info`

### ISSUE THREAD

**Issue by arjansingh** [kategengler/ember-cli-code-coverage#36]
Currently `lcov.info` namespaces addon code as: `SF:modules/addon-name/models/ab.js`

It should be: `SF:addon/models/ab.js` so that code coverage tools like Coveralls can properly parse the file.

I solved this using `sed s/SF:modules\\/addon-name/SF:addon/` in my build jobs, but we probably should work on properly renaming it and save everyone the trouble. If someone could point me to some lines or functions to look at for context, I'll take it on.

**Comment by rwjblue** [comment]
Yep, thanks for opening the issue.  Definitely needs to be addressed.  

Happy to chat through the issue with someone willing to do the work on fixing...

**Comment by offirgolan** [comment]
@rwjblue I got some time this week to work on this. We can discuss this further on slack if you're up for it.

**Comment by rwwagner90** [comment]
@rwjblue sounds like both @arjansingh and @offirgolan are willing to give it a try. I'm also willing to help out if needed, but would really love this to be implemented 😄

**Comment by rwjblue** [comment]
Absolutely, would love to get this fixed.  I haven't really looked into it too much to know what work would be needed.

[here](https://github.com/kategengler/ember-cli-code-coverage/blob/master/lib/attach-middleware.js#L23) is where we process the posted results from the test run, that seems like the most likely place to modify the JSON output before being written to disk.

**Comment by sglanzer** [comment]
@sandersky didn't we do modification of the module names after the coverage report - can we reuse that concept here?

**Comment by rwwagner90** [comment]
Just threw up a PR that will hopefully be satisfactory to resolve this issue, at least until someone has a better way to do it 😄
