### ISSUE TITLE
Addon tests never exit

### ISSUE THREAD

**Issue by alexlafroscia** [kategengler/ember-cli-code-coverage#37]
Been trying to get code coverage working for `ember-ajax` but am running into an issue.  When running

```bash
$ COVERAGE=true ember test
```

the tests start, run fine, and generate the `coverage` directory.  However, the process never exists.  Some configuration options that might be relevant:

- Test are run through Mocha
- `ember-cli v2.8.0`
- `ember-cli-pretender v0.7.0`
-  `pretender v1.2.0`

If you want to try it out, I've pushed a branch [here](https://github.com/ember-cli/ember-ajax/tree/add-code-coverage) with `ember-cli-code-coverage` installed and an old version of Pretender that I thought might be causing trouble removed (although it didn't help).

I dug into the Testem middleware a bit, thinking that might be the cause of the problem.  Everything seems to be working fine there; that code exists and all.  Not really sure where to look from there.

**Comment by alexlafroscia** [comment]
No idea if helpful, but I did notice something off when running with `DEBUG=*`.  There's a line in the log from `engine:ws` with the following information:

```
received "42["all-test-results",{"failed":0,"passed":154,"total":155,"pending":0, .....
```

And from there it's really long.  The numbers seem weird though, right? 154 passed, 155 total with none failing or pending?

**Comment by rwjblue** [comment]
Sounds like https://github.com/kategengler/ember-cli-code-coverage/issues/32, can you confirm?

**Comment by alexlafroscia** [comment]
Possibly?  I don't get any failing tests though, which that issue seems to have.

**Comment by alexlafroscia** [comment]
I can't even get things working on a fresh addon

```bash
$ ember addon demo-addon
$ cd demo-addon
$ ember install ember-cli-code-coverage
$ ember test
ok 1 PhantomJS 2.1 - JSHint | app.js: should pass jshint
ok 2 PhantomJS 2.1 - JSHint | helpers/destroy-app.js: should pass jshint
ok 3 PhantomJS 2.1 - JSHint | helpers/module-for-acceptance.js: should pass jshint
ok 4 PhantomJS 2.1 - JSHint | helpers/resolver.js: should pass jshint
ok 5 PhantomJS 2.1 - JSHint | helpers/start-app.js: should pass jshint
ok 6 PhantomJS 2.1 - JSHint | resolver.js: should pass jshint
ok 7 PhantomJS 2.1 - JSHint | router.js: should pass jshint
ok 8 PhantomJS 2.1 - JSHint | test-helper.js: should pass jshint

1..8
# tests 8
# pass  8
# skip  0
# fail  0

# ok

$ COVERAGE=true ember test
ok 1 PhantomJS 2.1 - JSHint | app.js: should pass jshint
ok 2 PhantomJS 2.1 - JSHint | helpers/destroy-app.js: should pass jshint
ok 3 PhantomJS 2.1 - JSHint | helpers/module-for-acceptance.js: should pass jshint
ok 4 PhantomJS 2.1 - JSHint | helpers/resolver.js: should pass jshint
ok 5 PhantomJS 2.1 - JSHint | helpers/start-app.js: should pass jshint
ok 6 PhantomJS 2.1 - JSHint | resolver.js: should pass jshint
ok 7 PhantomJS 2.1 - JSHint | router.js: should pass jshint
ok 8 PhantomJS 2.1 - JSHint | test-helper.js: should pass jshint
```

and from there, it hangs

**Comment by alexlafroscia** [comment]
Tried updating to `ember-cli@2.8.0` and re-generating the addon, but no luck there...

I'm wondering if something weird is happening by calling `Testem.afterTests`.  It seems weird that the pause happens before the summary of `1..8` etc etc, like Testem isn't getting the message that it needs to finish up.

**Comment by alexlafroscia** [comment]
Aaaaand it seems to be a Phantom issue.  If I set up Testem to run Chrome in CI, then everything works as expected.

**Comment by kategengler** [comment]
There's definitely something funny w/r/t Phantom + Testem + ember test in the last month or so, but I haven't been able to get it into a reproducible scenario. We've been running the top 100 addons ember-try nightly and a few fail because of phantom hanging.

**Comment by alexlafroscia** [comment]
Weird.  If you do the steps above locally (new addon w/ `ember-cli-code-coverage`) does it work?

BTW I've got Phantom 2.1.1 installed locally, AFAIK that's what it's running against.

**Comment by alexlafroscia** [comment]
Solution: don't use Phantom
