### ISSUE TITLE
[QUERY] Is it possible to generate the coverage for a specific file/spec module (integration)

### ISSUE THREAD

**Issue by hari-raj-e3870** [kategengler/ember-cli-code-coverage#372]
Instead of running `COVERAGE=true ember test` is it possible to pass a specific spec file path as an argument ?

**Comment by kategengler** [comment]
You can pass any supported arguments to `ember test`, including ones that filter. I often run my coverage separately for unit and acceptance tests.

**Comment by hari-raj-e3870** [comment]
> You can pass any supported arguments to `ember test`, including ones that filter. I often run my coverage separately for unit and acceptance tests.

Thank you for the reply, I am unable to find in the documentation the syntax to use, could you please add a small example of the code snippet to run separately based on arguement

**Comment by hari-raj-e3870** [comment]
> You can pass any supported arguments to `ember test`, including ones that filter. I often run my coverage separately for unit and acceptance tests.

Thank you Kate for the reply, it actually dint strike for me to consume the existing filter args thats can be passed for `ember test` along with `COVERAGE=true`

Hope what you meant was `COVERAGE=true ember test -f=<some integration test>`
