### ISSUE TITLE
Excludes not working as expected with addon

### ISSUE THREAD

**Issue by alexlafroscia** [kategengler/ember-cli-code-coverage#41]
Having now set up coverage for `ember-ajax`, I'm trying to get it working right.

The follow are the files that are having coverage calculated:

<img width="302" alt="screen shot 2016-09-17 at 6 31 24 pm" src="https://cloud.githubusercontent.com/assets/1645881/18612089/022466b8-7d05-11e6-819d-a9a358849eda.png">

However, I've tried to ignore the whole `tests/dummy` directory with the configuration [here](https://github.com/ember-cli/ember-ajax/blob/69df203c3b396142a4462186285c198d6df44c9a/config/coverage.js).  It seems like the files are not actually being ignored.

**Comment by srowhani** [comment]
I found that `/dummy/(.*)/` or something similar does the trick.

**Comment by rwwagner90** [comment]
@alexlafroscia still having this issue?

**Comment by konradjurk** [comment]
@alexlafroscia I ran into the same issue and were able to resolve it this way:

1. First change the output directory in your coverage config temporarily, just to make sure it is actually hit (`coverage.js` has to live under `configPath` from package.json).
2. Add a function to the `excludes` array that prints out the first positional argument which is the file path. This function is called for every file that the addon finds.

      Most paths are unexpectedly different to the ones you see in the IDE (e.g. `app` file tree is not present, probably because the dummy app is built so `dummy/app/router.js` becomes `dummy/router.js`).

    From here you can adjust your excluded files array so it is working as expected :)

**Comment by rwwagner90** [comment]
Thanks for the feedback @konradjurk! I think with this workaround, everything should be working as expected. Would you be interested in submitting a PR adding something about setup for addons to the README?

**Comment by rwwagner90** [comment]
I believe this should be resolved in the latest version, 1.0.0-beta.2. If it is not, please feel free to reopen!
