### ISSUE TITLE
How to view coverage files?

### ISSUE THREAD

**Issue by denchen** [kategengler/ember-cli-code-coverage#44]
Forgive me if this is a dumb question, but is there a way of viewing the generated coverage files from within Ember itself, or do I have to manually open those files on my computer from my web browser? As reference, I was using `ember-cli-blanket` previously, and I had the option of viewing coverage details when navigating to `http://localhost/tests?coverage`, which would run the tests and show coverage at the bottom. Does `ember-cli-code-coverage` have a similar option?

**Comment by rwwagner90** [comment]
@denchen you have to view the files manually I think. Just go in the coverage folder and open index.html

**Comment by BrianSipple** [comment]
@rwwagner90 yep, that's how I've been playing it so far. 

@denchen One idea that comes to mind is having an npm script that spins up something like `http-server` and opens your browser to the `coverage` directory:

```js
"scripts": {
  ...
  "serve:coverage": "http-server ./coverage/ -p 4242 -o"
}
```
But of course, that introduces the trade-off of extra dependencies for other developers, etc, etc -- so please don't treat that example as more than a whim 😄.

**Comment by rwwagner90** [comment]
I think we should document how to view the coverage and then close this issue. Thoughts @rwjblue or @kategengler?

**Comment by rwjblue** [comment]
Ya, sounds good...

**Comment by rwjblue** [comment]
I generally just `open coverage/index.html` and navigate in chrome via `file://`...
