### ISSUE TITLE
The coverage summary json is missing a '}' in the end

### ISSUE THREAD

**Issue by ssurana2** [kategengler/ember-cli-code-coverage#47]
Hi

After running `COVERAGE=true ember test` and opening `coverage_summary.json` file, the file shows that json is not totally formatted. And adding '}' in the end takes care of the issue. Just wanted to report the issue.

**Comment by rwjblue** [comment]
Hmm. Seems pretty odd. How large is the file?

**Comment by ssurana2** [comment]
its a 2.4 KB file. Have attached the txt version of the json file for your reference.
[coverage-summary.txt](https://github.com/kategengler/ember-cli-code-coverage/files/507717/coverage-summary.txt)

**Comment by ssurana2** [comment]
@rwjblue the plugin that I was using to prettify the json file in the txt file attached above had some issue. Because of which, I was a bit mislead to believe there is an issue in the json produced by ember-cli-code-coverage.
