### ISSUE TITLE
Addon support: no coverage for addon files on Windows

### ISSUE THREAD

**Issue by nfc036** [kategengler/ember-cli-code-coverage#48]
I did not get any coverage information for files within the addon subdirectory. This problem seems to be specific for windows environments. It seems, that the function [here](https://github.com/kategengler/ember-cli-code-coverage/blob/0b6ebaaf245739c255edbd5e2a557008ba11a683/index.js#L132)
```
 _doesFileExistIsCurrentProjectAddonModule: function(relativePath) {
    relativePath = path.join('addon', relativePath.replace(path.join('modules', this.project.pkg.name),''));

    if (this._existsSync(relativePath)) {
      return true;
    }

    return this._doesTemplateFileExist(relativePath);
  },
``` 
in index.js has problems with the path separator on Windows ("/" vs. "\"). Inserting `relativePath = path.join(relativePath);` as the first line in this function seems to solve this issue but this is most probably not the best solution. (I am not an expert on this...)

**Comment by rwjblue** [comment]
Lets break apart that line a bit, and update your local copy with the snippet below, then tell me what the console output values are..

```js
  doesFileExistIsCurrentProjectAddonModule: function(_relativePath) {
    console.log('_relativePath', _relativePath);
    var relativePathWithoutProjectNamePrefix = relativePath.replace(path.join('modules', this.project.pkg.name), '');
    console.log('relativePathWithoutProjectNamePrefix', relativePathWithoutProjectNamePrefix);

    var relativePath = path.join('addon', relativePathWithoutProjectNamePrefix);
    console.log('relativePath', relativePath);

    if (this._existsSync(relativePath)) {
      return true;
    }

    return this._doesTemplateFileExist(relativePath);
  },
```

I suspect, that we actually should be doing the following to cleanup/sanitize using `/` before checking `_existsSync`:

```js
    var relativePathWithoutProjectNamePrefix = relativePath.replace('modules' + '/' +  this.project.pkg.name, '');

    var relativePath = 'addon/' + relativePathWithoutProjectNamePrefix;
    console.log('relativePath', relativePath);
```

**Comment by nfc036** [comment]
Hi Robert, thanks for looking into this. Here the output for one file:
```
_relativePath modules/lib-ember-addon/transforms/tstamp.js
relativePathWithoutProjectNamePrefix modules/lib-ember-addon/transforms/tstamp.js
relativePath addon\modules\lib-ember-addon\transforms\tstamp.js
```

**Comment by nfc036** [comment]
Indeed, the second code snippet fixes the problem.

**Comment by rwjblue** [comment]
Submitted https://github.com/kategengler/ember-cli-code-coverage/pull/49 to fix.
