### ISSUE TITLE
Does not work with CoffeeScript

### ISSUE THREAD

**Issue by luketheobscure** [kategengler/ember-cli-code-coverage#55]
It looks like files compiled from CoffeeScript (using ember-cli-coffeescript) are not included when calculating code coverage. They don't show up on any of the reports.

**Comment by luketheobscure** [comment]
I've set up a demo app illustrating this bug: https://github.com/luketheobscure/ember-code-coverage-bug

I don't have the spare time to try to tackle this myself, but I would be happy to test things out.

**Comment by kategengler** [comment]
I wonder if this isn't about coffeescript but is actually another manifestation of this bug https://github.com/kategengler/ember-cli-code-coverage/issues/20

That issue was closed in version 0.3.6, could you see if using a newer version fixes this issue for you?

**Comment by luketheobscure** [comment]
I updated that demo app to 0.3.9, and it didn't fix the problem.

**Comment by luketheobscure** [comment]
Updated bug demo to use 0.3.12, still seeing the same issue. I would be happy to throw a little bit of time at this if you have any feedback on where to start.

**Comment by turboladen** [comment]
+1

**Comment by rwwagner90** [comment]
@luketheobscure without knowing the exact issue, I think the `before` or `after` of ember-cli-coffeescript needs to be tweaked to allow the addons to run in the proper order https://github.com/kimroen/ember-cli-coffeescript/blob/master/package.json#L74-L81

**Comment by rwwagner90** [comment]
Is there anyone using CoffeeScript that would like to test this out with the latest 1.0.0-beta.2?

**Comment by rwwagner90** [comment]
@luketheobscure @turboladen can either of your please test this out with the latest beta, 1.0.0-beta.3?

**Comment by luketheobscure** [comment]
I'm afraid we migrated all of our projects off of CoffeeScript. https://github.com/decaffeinate/decaffeinate is incredible.

**Comment by rwwagner90** [comment]
CoffeeScript works now, I've tested it on a project using it.
