### ISSUE TITLE
Not generating coverage reports

### ISSUE THREAD

**Issue by epchristi** [kategengler/ember-cli-code-coverage#56]
[When running tests with COVERAGE=true, not generating results.

config/coverage.js has:
module.exports = {
  reporters: ['lcov', 'html']
}

mirage/config.js has:
this.passthrough('/write-coverage');
(NOTE: When this was wrong, I got errors about ember not being able to POST to /write-coverage. Those errors are gone now)

I am running the tests like:
COVERAGE=true ember test 

The tests run, but no results output. How can I triage this? Not sure where to go, because no errors are getting reported. (except a "Building(node) warning: possible EventEmitter memory leak detected. 11 exit listeners added." warning)

**Comment by BrianSipple** [comment]
@epchristi Do you mind if I ask what editor you're using? 

I got trolled pretty hard by this a few days ago when using VSCode. Everything ran perfectly, but no `coverage` folder was to be found.

...then I collapsed and expanded the top-level folder :upside_down_face:.

**Comment by ming-codes** [comment]
Possibly related to #77 

Try `0.3.10`?

**Comment by rwwagner90** [comment]
Closing due to lack of response from @epchristi. If you are still having problems on the latest version, please feel free to open a new issue!
