### ISSUE TITLE
files from addons bleed into coverage results

### ISSUE THREAD

**Issue by kellyselden** [kategengler/ember-cli-code-coverage#7]
Not all the files in the picture are mine, some come from addons:
![capture2](https://cloud.githubusercontent.com/assets/602423/15271149/38a90e64-19f0-11e6-9704-aaff4255089b.PNG)

**Comment by kategengler** [comment]
Are the files that are from addons all from addon's app tree? Those are ones I've observed are mingled. How could I filter them out?

**Comment by benoror** [comment]
Can confirm addons files were instrumented too, which were responsible for the discrepancies. PR with @kellyselden changes concerning to **Addons files exclusion** only: https://github.com/kategengler/ember-cli-code-coverage/pull/10

**Comment by kategengler** [comment]
I still don't think all addon files bleed into coverage, just those that have been merged with the 'app' tree

**Comment by rwjblue** [comment]
Agreed, it should be the addon's `app` tree files that are bleeding in at the moment.

**Comment by sandersky** [comment]
Addressed this in #11 which I believe covers more edge cases than #10
