### ISSUE TITLE
Handle app in addon case

### ISSUE THREAD

**Issue by rwwagner90** [kategengler/ember-cli-code-coverage#70]
Unsure what we may need to handle here, as I think we want app included in coverage for addons, but was mentioned in talking with @rwjblue, so throwing up an issue to track.

cc @rwjblue

**Comment by rwjblue** [comment]
Yes, basically we need to tweak [this conditional](https://github.com/kategengler/ember-cli-code-coverage/blob/5c7e1a54b8a3776b53a4b41d01e17f08ae77cb5b/lib/coverage-instrumenter.js#L32) to look for `app/` and not `tests/dummy/app`.

**Comment by rwjblue** [comment]
Oh, wait, I think I missed the fallback case [here](https://github.com/kategengler/ember-cli-code-coverage/blob/5c7e1a54b8a3776b53a4b41d01e17f08ae77cb5b/lib/coverage-instrumenter.js#L37).


This is likely already working properly, sorry!
