### ISSUE TITLE
Ensure `app/` files are required for addon coverage.

### ISSUE THREAD

**Issue by rwjblue** [kategengler/ember-cli-code-coverage#73]
The current code that kicks off a `require` for each module will only require addon files in `addon/` directory. It does not include `app/` files (since they would be under `dummy` not `my-addon-name`).

In conjunction with https://github.com/kategengler/ember-cli-code-coverage/issues/71, we should also kick off require's for `dummy` when in an addon.

**Comment by adamjmcgrath** [comment]
This should be resolved in the latest release. The `require` get's called with every file that's instrumented - for addon's that's every file in the `addon` and `app` directory.

**Comment by rwwagner90** [comment]
This is done 👍
