### ISSUE TITLE
Template Files not Being Included in Coverage Report

### ISSUE THREAD

**Issue by danny-andrews** [kategengler/ember-cli-code-coverage#77]
Library Versions:
- ember: **2.4.3**
- ember-cli: **2.4.3**
- ember-cli-code-coverage: **0.3.2**

Pods? **Yes**

When I run tests with `COVERAGE=true` inside an addon, I don't see the templates included in the coverage like they are inside standard ember apps.

**Comment by rwwagner90** [comment]
@danny-andrews can you try the latest version, 0.3.8, just to see if anything has changed?

**Comment by danny-andrews** [comment]
I see the same behavior on `0.3.8`.

**Comment by rwjblue** [comment]
@danny-andrews - Is the addon public or can you create a demo repo so we can try to dig into this?

**Comment by ming-codes** [comment]
I had a similar issue with models not included in coverage report. Could be caused by process terminating before async file write completes. `0.3.10` should have it fixed

**Comment by PratheepV** [comment]
I am using the master still I am facing the templates(.hbs not being covered). We are writing acceptance tests.

**Comment by rwjblue** [comment]
https://github.com/kategengler/ember-cli-code-coverage/pull/103 adds custom instrumentation of templates, could use testing...
