### ISSUE TITLE
ember-test never terminates with COVERAGE=true

### ISSUE THREAD

**Issue by hoboman313** [kategengler/ember-cli-code-coverage#81]
ember-cli: 2.10.0 ( also repro in previous version )
ember: 2.10.0
ember-cli-code-coverage: 0.38.0

`ember t` everything is good with no errors and proper termination. `COVERAGE=true ember t` everything succeeds and the coverage is generated as expected, but the process never terminates. When I run it in DEBUG="*" mode it seems to hang with:
``` 
  engine:ws writing "3" +0ms
  engine:ws received "2" +25s
  engine:socket packet +0ms
  engine:socket got ping +0ms
  engine:socket sending packet "pong" (undefined) +0ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "3" +0ms
  engine:ws received "2" +25s
  engine:socket packet +0ms
  engine:socket got ping +0ms
  engine:socket sending packet "pong" (undefined) +0ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "3" +0ms
  engine:ws received "2" +25s
  engine:socket packet +0ms
  engine:socket got ping +0ms
  engine:socket sending packet "pong" (undefined) +0ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "3" +0ms
```

Looked into debugging phantom js but found no obvious errors.

**Comment by topaxi** [comment]
My builds stopped working with the same behaviour, it seemed to appear randomly. I guess this might be a dependency issue?

**Comment by rox163** [comment]
I've seen this as well but only with addons that have acceptance tests. If I skip the acceptance test then the run completes and reports coverage.

**Comment by hoboman313** [comment]
@rox163 Thank you! That was causing the freezing for me too.

**Comment by topaxi** [comment]
Are you by any chance using `ember-cli-mirage`?

I noticed that the `request.onload` callback never got called. This might be caused by pretenderjs (even though the request was made and I had a passthrough rule in `mirage/config.js`).

In my codebase in `tests/helpers/destroy-app.js` there was a missing line `server.shutdown();`.

Here the full file which solved the issue for me:

`tests/helpers/destroy-app.js`
```js
import Ember from 'ember';

export default function destroyApp(application) {
  Ember.run(application, 'destroy');
  server.shutdown();
}
```

**Comment by hoboman313** [comment]
That was exactly my problem too. Thank you. :astonished:

**Comment by mdarmetko** [comment]
Still having this issue with version 0.3.6 even with the above solution. Reverting to 0.2.2 fixed it for me.

**Comment by hoboman313** [comment]
The issue is back for me with 0.3.9 but 0.3.8 is still good

**Comment by kategengler** [comment]
#87 has been released in 0.3.10

**Comment by ming-codes** [comment]
Duplicates with #88?

**Comment by hoboman313** [comment]
I opened this ticket over a month before 88.
Anyways, the hanging issue is fixed for me after upgrading to 0.3.10 ( and previously having applied topaxi's fix ).

**Comment by mdarmetko** [comment]
Was still seeing this in 0.3.10. I'm using mostly default generated tests with ember 2.10 and ember-cli-mirage. It must have been a problem with a mirage instance never getting shutdown and hanging around.  Resolved it by adding `if(server !== undefined) { server.shutdown(); }` to beforeEach and afterEach in each acceptance test file. As in,
```
module('Acceptance: Metro', {
  beforeEach: function() {
    if(server !== undefined) { server.shutdown(); }
    application = startApp();
    originalConfirm = window.confirm;
    window.confirm = function() {
      confirmCalledWith = [].slice.call(arguments);
      return true;
    };
  },
  afterEach: function() {
    Ember.run(application, 'destroy');
    window.confirm = originalConfirm;
    confirmCalledWith = null;
    if(server !== undefined) { server.shutdown(); }
  }
});
```
Hope this helps someone else having the same problem.

**Comment by isaacaskew** [comment]
@topaxi - that mirage `server.shutdown()` trick saved my ass. If you're even in the Chicago area, your drink's on me.

**Comment by tniezurawski** [comment]
I had the same problem. Because of Integration tests where I use [New Testing API](https://github.com/emberjs/rfcs/blob/master/text/0232-simplify-qunit-testing-api.md#detailed-design).

I had to close mirage server (`server.shutdown()`) after every Integration tests. Here is quite neat solution for folks that will strugle with this in the future:

https://gist.github.com/tniezurawski/907d0fa83a7a621146add3871d1827ca
