### ISSUE TITLE
What is the best way to wdio or selenium test on the instrumented code and the coveragae result  

### ISSUE THREAD

**Issue by akhileshk** [kategengler/ember-cli-code-coverage#84]
Scenario : We are trying to deploy a instrumented ember App on a internal server and run test using wdio test runner or any other  test framework(Pytest). At the end of the test we will download the coverage result.

Our observation: What we have noticed that Unless we instrument and deploy the code on the same server where Istanbul middleware is running, we are not able to get the coverage information correctly. This is problematic when we have to run multipple different application. 

Question: Is there any suggestion how to handle this scenario in a best possible way?

**Comment by kategengler** [comment]
I'm afraid this is outside the realm of possibility for this addon. This addon provides code coverage for running ember tests through ember-cli, and requires many hooks provided by ember-cli to work.
