### ISSUE TITLE
config/coverage options for excludes don't seem to work

### ISSUE THREAD

**Issue by jbelmont** [kategengler/ember-cli-code-coverage#85]
I have this version of ember-cli-code-coverage in my package.json "ember-cli-code-coverage": "0.3.8". Also I have a coverage file in this root path in my ember app. 

config/coverage.js
```
module.exports = {
     // This is default value
    coverageEnvVar: 'COVERAGE',
     // More reporters found here https://github.com/gotwarlost/istanbul/tree/master/lib/report
    reporters: ['lcov', 'json', 'json-summary', 'text', 'text-summary'],
    // Defaults to ['*/mirage/**/*']
    excludes: [
        "/blueprints",
        "/config",
        "/public", 
        "/tmp", 
        "/tests/dummy/**",
        "/vendor"
    ],
    // Defaults to coverage. A folder relative to the root of your project to store coverage results.
    // Set to true or false if you are using ESNext features.
    useBabelInstrumenter: true
}
```

I have the following folder structure
➜  ember-webrtc-devices git:(master) tree -d -L 3 -I 'node_modules|bower_components'
.
├── addon
│   ├── components
│   │   └── device-selection
│   └── mixins
├── app
│   ├── components
│   │   └── device-selection
│   ├── mixins
│   └── translations
│       └── webrtc-devices
├── blueprints
│   └── ember-webrtc-devices
├── config
├── coverage
│   └── lcov-report
│       ├── addon
│       ├── app
│       └── tests
├── public
│   └── assets
│       └── sounds
├── scripts
├── tests
│   ├── dummy
│   │   ├── app
│   │   ├── config
│   │   └── public
│   ├── helpers
│   ├── integration
│   │   └── components
│   └── unit
│       └── mixins
├── tmp
├── typings
│   └── ember
└── vendor

36 directories

When I run `npm run coverage` which runs   "coverage": "COVERAGE=true ember test"

I got the following code coverage report.

------------------------------------|----------|----------|----------|----------|----------------|
File                                |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------------------|----------|----------|----------|----------|----------------|
 addon/components/device-selection/ |     62.5 |    53.85 |     62.5 |    57.14 |                |
  component.js                      |     62.5 |    53.85 |     62.5 |    57.14 |... ,97,115,126 |
 addon/mixins/                      |    29.82 |    19.74 |    33.33 |    25.23 |                |
  device-enumeration.js             |    29.82 |    19.74 |    33.33 |    25.23 |... 267,268,270 |
 app/components/device-selection/   |      100 |      100 |      100 |      100 |                |
  component.js                      |      100 |      100 |      100 |      100 |                |
 tests/dummy/app/                   |      100 |      100 |        0 |      100 |                |
  app.js                            |      100 |      100 |      100 |      100 |                |
  resolver.js                       |      100 |      100 |      100 |      100 |                |
  router.js                         |      100 |      100 |        0 |      100 |                |
 tests/dummy/app/initializers/      |      100 |      100 |      100 |      100 |                |
  webrtc-service.js                 |      100 |      100 |      100 |      100 |                |
 tests/dummy/app/services/          |        0 |      100 |        0 |        0 |                |
  webrtc.js                         |        0 |      100 |        0 |        0 |    13,14,18,19 |
------------------------------------|----------|----------|----------|----------|----------------|
All files                           |    41.04 |    28.43 |    43.18 |    36.25 |                |
------------------------------------|----------|----------|----------|----------|----------------|

=============================== Coverage summary ===============================
Statements   : 41.04% ( 71/173 ), 2 ignored
Branches     : 28.43% ( 29/102 )
Functions    : 43.18% ( 19/44 )
Lines        : 36.25% ( 58/160 )
================================================================================

Since I specifically excluded tests/dummy why is code coverage reporting it is touched

**Comment by adamjmcgrath** [comment]
`excludes` uses the module path rather than the file path, so you would need to exclude `dummy/tests/**` in `v0.3.8`

If you use the latest version the `tests/dummy` folder is not included

**Comment by rwwagner90** [comment]
Since @adamjmcgrath has provided a solution here, I am closing this. Please feel free to reopen if there is still an issue!
