### ISSUE TITLE
Support in-repo engine coverage

### ISSUE THREAD

**Issue by Nuzsk** [kategengler/ember-cli-code-coverage#86]
Ember-engines allow use [in-repo style](https://github.com/ember-engines/ember-engines#creating-engines) of engine location, [in this case](https://github.com/ember-engines/ember-engines#unitintegration-testing-for-in-repo-engines) testing results of main app includes testing results of engine. But code coverage output, unlike tap file, not includes coverage results for engine.

Steps to reproduce:
- git clone https://github.com/Nuzsk/ember-engine-coverage-test.git
- cd ember-engine-coverage-test && npm install && bower install
- COVERAGE=true ember test > test-results.tap
- cat test-results.tap | grep test-me
- cat coverage/coverage-summary.json | grep test-me

**Comment by rwwagner90** [comment]
This seems to be fixed now, and I just wrote a test for engines here https://github.com/kategengler/ember-cli-code-coverage/pull/162. If you are still experiencing issues on 1.0.0-beta.2 please let us know!
