### ISSUE TITLE
CI hangs when updating 0.3.8 => 0.3.9

### ISSUE THREAD

**Issue by kellyselden** [kategengler/ember-cli-code-coverage#88]
I just upgraded to 0.3.8 successfully using `useBabelInstrumenter`. Now trying to get to the latest version, but it hangs CI.

https://travis-ci.org/kellyselden/package-hint-historic-resolver/builds/188068217
https://github.com/kellyselden/package-hint-historic-resolver/pull/300/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34

**Comment by omarkohl** [comment]
Same here.

It can also be reproduced locally (not just CI) but it only happens when using PhantomJS (e.g. with Chrome it runs fine).

In our case it hangs while running JSLint.

The following two examples run fine:

* COVERAGE=true ember test --launch Chromium
* ember test --launch PhantomJS

This one hangs:

* COVERAGE=true ember test --launch PhantomJS

**Comment by SergeAstapov** [comment]
Have the same problem.
#87 works for me with PhantomJS

**Comment by hoboman313** [comment]
I reported this earlier with #81 
I found no solution but to downgrade back to 0.38

**Comment by kategengler** [comment]
Hopefully solved by #87

**Comment by kategengler** [comment]
#87 has been released in 0.3.10

**Comment by kellyselden** [comment]
I'm now seeing `Cannot find module 'rsvp'` with 0.3.10

https://travis-ci.org/kellyselden/package-hint-historic-resolver/jobs/189337365#L651

**Comment by ming-codes** [comment]
I'm having the same problem with `0.3.10`.

**Comment by ming-codes** [comment]
@kategengler Submitted PR to fix this issue

**Comment by samtsai** [comment]
https://github.com/kategengler/ember-cli-code-coverage/issues/88#issuecomment-270784595 is coming from changes introduced here:
https://github.com/kategengler/ember-cli-code-coverage/pull/83

I don't know of this has to do with different versions of node/npm.

I'm able to reproduce with:
"node":"0.12.9",
"npm":"2.14.9"

**Comment by samtsai** [comment]
@kellyselden seems like we squashed this one with `0.3.11` release changes, can you confirm?

**Comment by kellyselden** [comment]
Confirmed with two different apps. Thanks everyone.

**Comment by omarkohl** [comment]
0.3.11 works for us as well. Thanks!
